In [1]:
import pandas as pd
import unicodedata

# 0 Funcoes

In [2]:
# Como estamos importando de um excel, vamos ter que ajustar o nome das colunas
def normalizar_colunas(df):
    def remover_acentos(texto):
        return ''.join(
            c for c in unicodedata.normalize('NFKD', texto)
            if not unicodedata.combining(c)
        )

    df = df.copy()
    df.columns = [
        remover_acentos(col)
            .lower()
            .replace(' ', '_')
        for col in df.columns
    ]

    return df

In [3]:
# Como vamos juntar alguns dataframes, é melhor que estejam com os mesmos nomes algumas colunas
def renomear_colunas(df, mapa_colunas):
    """
    Parâmetros:
    df (pd.DataFrame): DataFrame original
    mapa_colunas (dict): {'nome_antigo': 'nome_novo'}

    Retorna:
    pd.DataFrame: DataFrame com colunas renomeadas
    """
    df = df.copy()

    # Aplica somente às colunas que existem no DataFrame
    mapa_valido = {
        col_antiga: col_nova
        for col_antiga, col_nova in mapa_colunas.items()
        if col_antiga in df.columns
    }

    df.rename(columns=mapa_valido, inplace=True)
    return df

In [4]:
"""
Como os dataframes tem colunas diferentes, na hora de juntar essa função irá ajudar.
Iremos adicionar colunas nos outros dataframes para que a junção possa ocorrer (as colunas terão dasdos vazios)
"""
def adaptar_dataframe(df, colunas_base, origem, lista_ids):
    df=df.copy()

     # filtra apenas os IDs desejados
    df = df[df['ra'].isin(lista_ids)]

    # adiciona colunas que faltam
    for col in colunas_base:
        if col not in df.columns:
            df[col] = pd.NA

    # mantém apenas as colunas do principal
    df = df[colunas_base]

    # cria coluna de origem
    df['ano_dataframe'] = origem

    return df

In [5]:
# Função correção de tipo de colunas
def corrigir_dados(tipo, dataframe, colunas):
    """
    Corrige o tipo de dados de colunas de um DataFrame.

    Parâmetros:
    tipo (str): tipo alvo ('int', 'float', 'str', 'data')
    dataframe (pd.DataFrame): DataFrame original
    colunas (list ou str): coluna ou lista de colunas

    Retorna:
    pd.DataFrame: DataFrame com colunas corrigidas
    """
    df = dataframe.copy()

    if isinstance(colunas, str):
        colunas = [colunas]

    match tipo.lower():
        case 'int':
            for col in colunas:
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

        case 'float':
            for col in colunas:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        case 'str':
            for col in colunas:
                df[col] = df[col].astype(str).str.strip()

        case 'data' | 'datetime':
            for col in colunas:
                df[col] = pd.to_datetime(df[col], errors='coerce')

        case _:
            raise ValueError(
                f"Tipo '{tipo}' não suportado. "
                "Use: int, float, str, data"
            )

    return df

In [6]:
def colunas_totalmente_vazias(df):
    """
    Identifica colunas que possuem apenas valores vazios e deleta

    Parâmetros:
    df (pd.DataFrame): DataFrame de entrada
    remover (bool): se True, remove as colunas vazias

    Retorna:
    pd.DataFrame:
        - DataFrame sem colunas vazias (remover=True)
    """
    df_tmp = df.copy()

    # considera strings vazias como NaN
    df_tmp = df_tmp.replace(r'^\s*$', pd.NA, regex=True)

    colunas_vazias = [
        col for col in df_tmp.columns
        if df_tmp[col].isna().all()
    ]

    return df_tmp.drop(columns=colunas_vazias)

In [7]:
def arredondar_floats(df, casas=2):
    """
    Arredonda todas as colunas float de um DataFrame.

    Parâmetros:
    df (pd.DataFrame): DataFrame de entrada
    casas (int): número de casas decimais (padrão = 2)

    Retorna:
    pd.DataFrame: DataFrame com floats arredondados
    """
    df = df.copy()

    colunas_float = df.select_dtypes(include=['float', 'float64', 'float32']).columns

    df[colunas_float] = df[colunas_float].round(casas)

    return df

# 1 Importando os dados

In [23]:
arquivo = r"https://raw.githubusercontent.com/vbomura/tc5/0afbe2d22ee4658c81a7470b2360a2aef3cd032e/Base_Passos_Magicos/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx"

# Pegando o dado de cada aba
base_2022 = pd.read_excel(arquivo, sheet_name="PEDE2022")
base_2023 = pd.read_excel(arquivo, sheet_name="PEDE2023")
base_2024 = pd.read_excel(arquivo, sheet_name="PEDE2024")

## Ajustes nas colunas

In [24]:
# Vamos padronizar os nomes das colunas
base_2022 = normalizar_colunas(base_2022)
base_2023 = normalizar_colunas(base_2023)
base_2024 = normalizar_colunas(base_2024)

In [25]:
# Renomeando algumas colunas das bases
mapa = {
    'pedra_23': 'ignorar' #tem uma coluna "repetida no dataframe, vamos ignorar ela pq não tem a info que precisamos"
    ,'pedra_2023': 'pedra_23'
    ,'inde_23': 'ignorar2'
    ,'inde_2023': 'inde_23'
}
base_2023 = renomear_colunas(base_2023, mapa)

mapa = {
    'portug': 'por'
    ,'ingles': 'ing'
    ,'matem': 'mat'
    ,'defas': 'defasagem'
    ,'idade_22': 'idade'
    
}
base_2022 = renomear_colunas(base_2022, mapa)

In [30]:
# Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023['ra'].unique().tolist()
ra_2022_diferentes = base_2022['ra'].unique().tolist()

# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

base_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes)

In [32]:
base_2022[['nome_anonimizado','ian']]

     nome_anonimizado   ian
31          Aluno-684  10.0
33          Aluno-857   5.0
36          Aluno-690   5.0
39          Aluno-693  10.0
40          Aluno-675  10.0
...               ...   ...
1005         Aluno-29  10.0
1006         Aluno-17  10.0
1007         Aluno-21  10.0
1008         Aluno-25  10.0
1009          Aluno-2  10.0

[600 rows x 2 columns]

In [33]:
base_2023[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0           Aluno-861  10.0
1           Aluno-862   5.0
2           Aluno-863  10.0
3           Aluno-864  10.0
4           Aluno-865  10.0
...               ...   ...
1009          Aluno-2  10.0
1010       Aluno-1271  10.0
1011       Aluno-1272  10.0
1012       Aluno-1273  10.0
1013       Aluno-1274  10.0

[1014 rows x 2 columns]

In [34]:
base_2024[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0          Aluno-1275  10.0
1          Aluno-1276  10.0
2          Aluno-1277  10.0
3           Aluno-868   5.0
4          Aluno-1278   5.0
...               ...   ...
1151       Aluno-1658  10.0
1152       Aluno-1659  10.0
1153       Aluno-1252  10.0
1154       Aluno-1660  10.0
1155       Aluno-1661  10.0

[1156 rows x 2 columns]

In [54]:
# Renomeando a coluna ian em cada dataframe
df_2022 = base_2022.rename(columns={"ian": "ian_2022"})
df_2023 = base_2023.rename(columns={"ian": "ian_2023"})
df_2024 = base_2024.rename(columns={"ian": "ian_2024"})

# Merge 2022 com 2023
df_merge = pd.merge(
    df_2022[["nome_anonimizado", "ian_2022"]],
    df_2023[["nome_anonimizado", "ian_2023"]],
    on="nome_anonimizado",
    how="outer"   # use 'inner' se quiser apenas quem existe nos dois anos
)

# Merge com 2024
df_final = pd.merge(
    df_merge,
    df_2024[["nome_anonimizado", "ian_2024"]],
    on="nome_anonimizado",
    how="outer"
)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024
0          Aluno-1      10.0      10.0      10.0
1       Aluno-1000       NaN      10.0      10.0
2       Aluno-1001       NaN       5.0       5.0
3       Aluno-1002       NaN       5.0       5.0
4       Aluno-1003       NaN      10.0       5.0

In [ ]:
df_final.describe

<bound method NDFrame.describe of      nome_anonimizado  ian_2023  ian_2024  ian_igual_todos_anos
0             Aluno-1      10.0      10.0                  True
1          Aluno-1000      10.0      10.0                  True
2          Aluno-1001       5.0       5.0                  True
3          Aluno-1002       5.0       5.0                  True
4          Aluno-1003      10.0       5.0                 False
...               ...       ...       ...                   ...
1400        Aluno-995       5.0       5.0                  True
1401        Aluno-996       5.0       NaN                  True
1402        Aluno-997      10.0       NaN                  True
1403        Aluno-998       5.0       NaN                  True
1404        Aluno-999       5.0       NaN                  True

[1405 rows x 4 columns]>

In [ ]:
def valores_iguais(row):
    valores = row.dropna().unique()
    return len(valores) <= 1  # 0 ou 1 valor distinto → todos iguais

df_final["ian_igual_todos_anos"] = df_final[
    ["ian_2022","ian_2023", "ian_2024"]
].apply(valores_iguais, axis=1)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024  ian_igual_todos_anos
0          Aluno-1      10.0      10.0      10.0                  True
1       Aluno-1000       NaN      10.0      10.0                  True
2       Aluno-1001       NaN       5.0       5.0                  True
3       Aluno-1002       NaN       5.0       5.0                  True
4       Aluno-1003       NaN      10.0       5.0                 False

In [56]:
df_ian_2022_menor_10 = df_final[df_final["ian_2022"] < 10]

qtdeIAN_2022 = df_ian_2022_menor_10.shape[0]
print(f"{qtdeIAN_2022} - Alunos em 2023 estao moderadamente ou severamente defasados")


df_ian_2023_menor_10 = df_final[df_final["ian_2023"] < 10]

qtdeIAN_2023 = df_ian_2023_menor_10.shape[0]
print(f"{qtdeIAN_2023} - Alunos em 2023 estao moderadamente ou severamente defasados")

df_ian_2024_menor_10 = df_final[df_final["ian_2024"] < 10]

qtdeIAN_2024 = df_ian_2024_menor_10.shape[0]
print(f"{qtdeIAN_2024} - Alunos em 2024 estao moderadamente ou severamente defasados")

#534

366 - Alunos em 2023 estao moderadamente ou severamente defasados
552 - Alunos em 2023 estao moderadamente ou severamente defasados
534 - Alunos em 2024 estao moderadamente ou severamente defasados

## Analise

1. Adequação do nível (IAN): Qual é o perfil geral de defasagem dos
alunos (IAN) e como ele evolui ao longo do ano?
(Ex.: quantos alunos estão moderadamente ou severamente defasados?)

In [41]:
df_divergentes = df_final[df_final["ian_igual_todos_anos"] == False]

df_divergentes.describe

df_divergentes

     nome_anonimizado  ian_2023  ian_2024  ian_igual_todos_anos
4          Aluno-1003      10.0       5.0                 False
5          Aluno-1004      10.0       5.0                 False
7          Aluno-1006      10.0       5.0                 False
9          Aluno-1008      10.0       5.0                 False
10         Aluno-1009      10.0       5.0                 False
...               ...       ...       ...                   ...
1381        Aluno-978      10.0       5.0                 False
1382        Aluno-979      10.0       5.0                 False
1385        Aluno-981      10.0       5.0                 False
1393        Aluno-989       5.0      10.0                 False
1399        Aluno-994      10.0       5.0                 False

[262 rows x 4 columns]

## Juntando os dataframes

In [11]:
# Vamos juntar os dataframes, mas primeiro vamos evitar juntar casos que já estão 2024
ra_principal = set(base_2024['ra'])

base_2023_filtrado = base_2023[
    (~base_2023['ra'].isin(ra_principal)) #alguns valores estão com problemas,
]

ra_principal.update(base_2023_filtrado['ra'].unique()) #marca os de 2023 para evitar duplicados que tem apenas entre 23 e 22

base_2022_filtrado = base_2022[
    (~base_2022['ra'].isin(ra_principal))
]

# Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023_filtrado['ra'].unique().tolist()
ra_2022_diferentes = base_2022_filtrado['ra'].unique().tolist()

In [12]:
# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

# Colocamos as colunas nos dataframes, para que eles fiquem 'parecidos' com 2024, e também uma coluna para saber de qual ano veio a info
base_2024['ano_dataframe'] = 2024
base_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes)

In [13]:
# Após todos os tratamentos, juntamos tudo
df_unificado = pd.concat(
    [base_2024, base_2023, base_2022],
    ignore_index=True
)

## Limpeza e correção dos dados dataframe

In [14]:
# Primeiro vamos corrigir o tipo de algumas colunas
colunas_correcao = ['inde_2024', 'inde_22', 'inde_23']
df_unificado = corrigir_dados('float', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser float

colunas_correcao = ['data_de_nasc']
df_unificado = corrigir_dados('data', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser data

colunas_correcao = ['idade']
df_unificado = corrigir_dados('int', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser data

In [15]:
# Retirando colunas com valores apenas vazios, após análises não vi valor em manter ou tentar preencher
df_unificado = colunas_totalmente_vazias(df_unificado)
df_unificado = df_unificado.drop(columns=['avaliador1','avaliador2','avaliador3','avaliador4','avaliador5','avaliador6'], errors='ignore') #essas colunas não trazem nenhum valor para a análise

In [16]:
# Correções e ajustes no valores da tabela
df_unificado = arredondar_floats(df_unificado)

# Testes

In [17]:
df_unificado.sample(50)

,ra,fase,inde_2024,pedra_2024,turma,nome_anonimizado,data_de_nasc,idade,genero,ano_ingresso,...,por,ing,ipv,ian,fase_ideal,defasagem,escola,ativo/_inativo,ativo/_inativo.1,ano_dataframe
806,RA-1569,4B,5.72,Quartzo,4B,Aluno-1569,2007-10-24 00:00:00,17,Feminino,2024,...,3.0,1.5,6.92,5.0,Fase 6 (2° EM),-2,EE Alexandre Rodrigues Nogueira,Cursando,Cursando,2024
504,RA-665,2M,5.70,Quartzo,2M,Aluno-665,2011-12-07 00:00:00,12,Feminino,2022,...,6.5,NaN,5.44,5.0,Fase 3 (7° e 8° ano),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
13,RA-889,ALFA,8.19,Topázio,ALFA B - G2/G3,Aluno-889,2015-07-07 00:00:00,9,Masculino,2023,...,9.5,NaN,8.28,5.0,Fase 1 (3° e 4° ano),-1,EM Maria Ignez Concelles Irma Ines,Cursando,Cursando,2024
436,RA-707,2G,6.50,Agata,2G,Aluno-707,2012-03-01 00:00:00,12,Feminino,2021,...,6.0,NaN,6.42,5.0,Fase 3 (7° e 8° ano),-1,EE João Ortiz Rodrigues,Cursando,Cursando,2024
989,RA-280,5N,8.82,Topázio,5N,Aluno-280,2009-07-04 00:00:00,15,Feminino,2021,...,8.0,10.0,8.67,10.0,Fase 4 (9° ano),1,Colégio Arco Íris Evolução,Cursando,Cursando,2024
514,RA-1499,2N,7.91,Ametista,2N,Aluno-1499,2012-11-03 00:00:00,12,Feminino,2024,...,7.0,NaN,7.11,10.0,Fase 2 (5° e 6° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1043,RA-246,7E,4.74,Quartzo,7E,Aluno-246,2009-04-08 00:00:00,15,Masculino,2022,...,0.0,0.0,7.50,10.0,Fase 5 (1° EM),2,FIAP School - SP,Cursando,Cursando,2024
1031,RA-269,7E,8.48,Topázio,7E,Aluno-269,2009-03-28 00:00:00,15,Masculino,2022,...,8.6,7.9,7.50,10.0,Fase 5 (1° EM),2,FIAP School - SP,Cursando,Cursando,2024
391,RA-1455,2A,6.64,Agata,2A,Aluno-1455,2012-04-23 00:00:00,12,Feminino,2024,...,3.5,NaN,7.83,5.0,Fase 3 (7° e 8° ano),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
40,RA-1298,ALFA,7.58,Ametista,ALFA E - G2/G3,Aluno-1298,2016-04-25 00:00:00,8,Masculino,2024,...,6.5,NaN,7.39,10.0,ALFA (1° e 2° ano),0,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando,2024
1265,RA-574,FASE 2,NaN,NaN,2F,Aluno-574,2012-10-02 00:00:00,<NA>,Masculino,2022,...,8.5,NaN,8.17,10.0,Fase 2 (5° e 6° ano),0,NaN,NaN,NaN,2023
718,RA-667,3M,7.18,Ametista,3M,Aluno-667,2011-04-22 00:00:00,13,Masculino,2021,...,4.5,4.0,6.97,10.0,Fase 3 (7° e 8° ano),0,EM Cecilia Cristina de Oliveira Rodrigues,Cursando,Cursando,2024
938,RA-1608,5D,7.07,Ametista,5D,Aluno-1608,2009-04-19 00:00:00,15,Masculino,2024,...,3.5,3.0,6.83,10.0,Fase 5 (1° EM),0,EE Paschoal Carlos Magno,Cursando,Cursando,2024
295,RA-1052,1J,7.74,Ametista,1J,Aluno-1052,2014-06-04 00:00:00,10,Masculino,2023,...,8.0,NaN,8.50,5.0,Fase 2 (5° e 6° ano),-1,EM Maria Ignez Concelles Irma Ines,Cursando,Cursando,2024
1358,RA-159,FASE 4,NaN,NaN,4N,Aluno-159,2007-08-28 00:00:00,16,Feminino,2021,...,6.0,7.8,7.88,5.0,Fase 6 (2° EM),-2,NaN,NaN,NaN,2023
1318,RA-300,FASE 3,NaN,NaN,3K,Aluno-300,2008-03-19 00:00:00,15,Masculino,2022,...,5.3,3.8,6.59,5.0,Fase 5 (1° EM),-2,NaN,NaN,NaN,2023
958,RA-274,5L,8.65,Topázio,5L,Aluno-274,2011-02-18 00:00:00,13,Feminino,2021,...,9.0,10.0,8.23,10.0,Fase 3 (7° e 8° ano),2,Colégio Arco Íris Evolução,Cursando,Cursando,2024
185,RA-1383,ALFA,8.37,Topázio,ALFA U - G2/G3,Aluno-1383,2016-04-23 00:00:00,8,Feminino,2024,...,7.0,NaN,7.50,10.0,ALFA (1° e 2° ano),0,EE Luiz Schunck,Cursando,Cursando,2024
9,RA-1281,ALFA,7.98,Ametista,ALFA B - G2/G3,Aluno-1281,2015-02-20 00:00:00,9,Feminino,2024,...,8.5,NaN,7.78,5.0,Fase 1 (3° e 4° ano),-1,EE Chácara Florida II,Cursando,Cursando,2024
849,RA-470,4L,6.98,Agata,4L,Aluno-470,2009-08-19 00:00:00,15,Feminino,2021,...,4.0,2.5,6.50,10.0,Fase 4 (9° ano),0,EE Maria André Schunck Dona,Cursando,Cursando,2024
1341,RA-240,FASE 4,NaN,NaN,4F,Aluno-240,2009-08-01 00:00:00,<NA>,Feminino,2017,...,3.3,4.2,6.92,10.0,Fase 4 (9° ano),0,NaN,NaN,NaN,2023
1197,RA-976,ALFA,NaN,NaN,ALFA R - G0/G1,Aluno-976,2015-04-04 00:00:00,<NA>,Masculino,2023,...,8.2,NaN,8.34,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,2023
375,RA-801,1R,6.68,Agata,1R,Aluno-801,2013-12-11 00:00:00,10,Masculino,2022,...,9.0,NaN,5.74,5.0,Fase 2 (5° e 6° ano),-1,EE Luiz Schunck,Cursando,Cursando,2024
746,RA-458,3P,5.68,Quartzo,3P,Aluno-458,2009-09-12 00:00:00,15,Masculino,2021,...,4.0,5.0,6.83,5.0,Fase 4 (9° ano),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
834,RA-1579,4F,7.89,Ametista,4F,Aluno-1579,2008-02-21 00:00:00,16,Feminino,2022,...,6.0,8.0,9.27,5.0,Fase 6 (2° EM),-2,EE Joaquim Mendes Feliz,Cursando,Cursando,2024
821,RA-236,4F,6.98,Agata,4F,Aluno-236,2010-06-21 00:00:00,14,Feminino,2022,...,4.0,8.0,6.36,10.0,Fase 4 (9° ano),0,EE Loris Nassif Mattar Profa,Cursando,Cursando,2024
1110,RA-59,8F,NaN,NaN,8F,Aluno-59,2005-10-11 00:00:00,19,Masculino,2022,...,NaN,NaN,NaN,10.0,Fase 8 (Universitários),0,Faculdade FIAP,Cursando,Cursando,2024
1172,RA-901,ALFA,NaN,NaN,ALFA E - G2/G3,Aluno-901,2012-12-30 00:00:00,10,Masculino,2023,...,7.3,NaN,8.60,5.0,Fase 2 (5° e 6° ano),-2,NaN,NaN,NaN,2023
966,RA-1616,5M,7.15,Ametista,5M,Aluno-1616,2007-09-06 00:00:00,17,Feminino,2024,...,6.5,6.5,7.12,5.0,Fase 6 (2° EM),-1,Estuda em outra cidade,Cursando,Cursando,2024
1027,RA-64,7A,8.74,Topázio,7A,Aluno-64,2006-07-06 00:00:00,18,Feminino,2021,...,6.5,10.0,8.28,10.0,Fase 7 (3° EM),0,Colégio Arco Íris Evolução,Cursando,Cursando,2024
1378,RA-1209,FASE 5,NaN,NaN,5M,Aluno-1209,2007-10-23 00:00:00,16,Feminino,2023,...,5.7,8.8,7.71,5.0,Fase 6 (2° EM),-1,NaN,NaN,NaN,2023
534,RA-652,2P,7.36,Ametista,2P,Aluno-652,2013-06-02 00:00:00,11,Feminino,2022,...,6.5,NaN,7.66,10.0,Fase 2 (5° e 6° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1078,RA-13,8D,NaN,NaN,8D,Aluno-13,2004-11-20 02:00:00,19,Masculino,2021,...,NaN,NaN,NaN,10.0,Fase 8 (Universitários),0,Universidade Santo Amaro (UNISA),Cursando,Cursando,2024
1063,RA-1250,8B,NaN,NaN,8B,Aluno-1250,2003-07-08 03:00:00,21,Masculino,2021,...,NaN,NaN,NaN,10.0,Fase 8 (Universitários),0,Universidade Cruzeiro do Sul,Cursando,Cursando,2024
823,RA-239,4F,6.78,Agata,4F,Aluno-239,2007-05-22 00:00:00,17,Feminino,2021,...,10.0,6.0,8.50,2.5,Fase 7 (3° EM),-3,EE Paschoal Carlos Magno,Cursando,Cursando,2024
1395,RA-84,FASE 6,NaN,NaN,6L,Aluno-84,2005-11-10 00:00:00,<NA>,Feminino,2018,...,5.8,5.5,7.67,5.0,Fase 8 (Universitários),-2,NaN,NaN,NaN,2023
882,RA-1593,4N,6.64,Agata,4N,Aluno-1593,2008-11-15 00:00:00,15,Masculino,2024,...,6.5,4.0,8.54,5.0,Fase 5 (1° EM),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
969,RA-286,5M,5.12,Quartzo,5M,Aluno-286,2007-11-20 00:00:00,16,Feminino,2022,...,0.0,4.5,5.78,5.0,Fase 6 (2° EM),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
57,RA-1309,ALFA,8.38,Topázio,ALFA H - G0/G1,Aluno-1309,2016-12-27 00:00:00,7,Feminino,2024,...,7.0,NaN,8.22,10.0,ALFA (1° e 2° ano),0,EM Maria Ignez Concelles Irma Ines,Cursando,Cursando,2024
130,RA-929,ALFA,7.72,Ametista,ALFA O - G2/G3,Aluno-929,2015-10-22 00:00:00,9,Feminino,2023,...,6.5,NaN,7.58,5.0,Fase 1 (3° e 4° ano),-1,EM Amanda Consuelo da Cunha,Cursando,Cursando,2024
1212,RA-1011,ALFA,NaN,NaN,ALFA Y - G0/G1,Aluno-1011,2015-03-11 00:00:00,<NA>,Masculino,2023,...,4.8,NaN,7.68,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,2023
1310,RA-386,FASE 3,NaN,NaN,3G,Aluno-386,2009-02-09 00:00:00,<NA>,Masculino,2019,...,3.7,1.2,6.63,5.0,Fase 4 (9° ano),-1,NaN,NaN,NaN,2023
1256,RA-1086,FASE 2,NaN,NaN,2C,Aluno-1086,2011-06-21 00:00:00,12,Feminino,2023,...,5.3,NaN,8.76,5.0,Fase 3 (7° e 8° ano),-1,NaN,NaN,NaN,2023
990,RA-1201,5N,8.38,Topázio,5N,Aluno-1201,2008-02-18 00:00:00,16,Masculino,2023,...,8.0,10.0,8.56,5.0,Fase 6 (2° EM),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
117,RA-1344,ALFA,9.36,Topázio,ALFA N - G2/G3,Aluno-1344,2016-07-25 00:00:00,8,Feminino,2024,...,10.0,NaN,9.43,10.0,ALFA (1° e 2° ano),0,EE Helio Luiz Dobrochinski Prof,Cursando,Cursando,2024
747,RA-1552,3P,7.44,Ametista,3P,Aluno-1552,2011-02-23 00:00:00,13,Masculino,2024,...,4.5,4.0,7.16,10.0,Fase 3 (7° e 8° ano),0,EM Cecilia Cristina de Oliveira Rodrigues,Cursando,Cursando,2024
646,RA-573,3G,7.84,Ametista,3G,Aluno-573,2011-08-04 00:00:00,13,Masculino,2021,...,3.5,5.5,6.83,10.0,Fase 3 (7° e 8° ano),0,EE João Ortiz Rodrigues,Cursando,Cursando,2024
284,RA-1421,1H,7.13,Ametista,1H,Aluno-1421,2013-10-14 00:00:00,11,Masculino,2024,...,7.0,NaN,7.16,5.0,Fase 2 (5° e 6° ano),-1,EM Pedro Antonio de Almeida,Cursando,Cursando,2024
800,RA-1566,4B,7.76,Ametista,4B,Aluno-1566,2007-09-03 00:00:00,17,Feminino,2024,...,8.0,8.5,8.34,5.0,Fase 6 (2° EM),-2,EE Alexandre Rodrigues Nogueira,Cursando,Cursando,2024
1258,RA-1091,FASE 2,NaN,NaN,2C,Aluno-1091,2011-10-15 00:00:00,12,Masculino,2023,...,9.7,NaN,9.17,5.0,Fase 3 (7° e 8° ano),-1,NaN,NaN,NaN,2023

In [19]:
df_unificado.to_excel('meus_dados.xlsx', index=False)

print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

Arquivo 'meus_dados.xlsx' criado com sucesso!

In [ ]:
base_2022[['nome_anonimizado','ian']]

Empty DataFrame
Columns: [nome_anonimizado, ian]
Index: []

In [18]:
df_unificado.dtypes

# df_unificado['destaque_ieg'].describe()
# df_unificado['destaque_ieg'].sample(50)
# df_unificado['cg'].isna().sum()
# df.nunique().sort_values()

ra                               object
fase                             object
inde_2024                       float64
pedra_2024                       object
turma                            object
nome_anonimizado                 object
data_de_nasc             datetime64[ns]
idade                             Int64
genero                           object
ano_ingresso                      int64
instituicao_de_ensino            object
pedra_20                         object
pedra_21                         object
pedra_22                         object
pedra_23                         object
inde_22                         float64
inde_23                         float64
no_av                           float64
iaa                             float64
ieg                             float64
ips                             float64
ipp                             float64
ida                             float64
mat                             float64
por                             float64
ing                             float64
ipv                             float64
ian                             float64
fase_ideal                       object
defasagem                         int64
escola                           object
ativo/_inativo                   object
ativo/_inativo.1                 object
ano_dataframe                     int64
dtype: object