In [265]:
import pandas as pd
import unicodedata
import re
import funcoes

# 1 Importando os dados

In [266]:
arquivo = r"https://raw.githubusercontent.com/vbomura/tc5/0afbe2d22ee4658c81a7470b2360a2aef3cd032e/Base_Passos_Magicos/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx"

# Pegando o dado de cada aba
base_2022 = pd.read_excel(arquivo, sheet_name="PEDE2022")
base_2023 = pd.read_excel(arquivo, sheet_name="PEDE2023")
base_2024 = pd.read_excel(arquivo, sheet_name="PEDE2024")

In [267]:
base_2022.columns

Index(['RA', 'Fase', 'Turma', 'Nome', 'Ano nasc', 'Idade 22', 'Gênero',
       'Ano ingresso', 'Instituição de ensino', 'Pedra 20', 'Pedra 21',
       'Pedra 22', 'INDE 22', 'Cg', 'Cf', 'Ct', 'Nº Av', 'Avaliador1',
       'Rec Av1', 'Avaliador2', 'Rec Av2', 'Avaliador3', 'Rec Av3',
       'Avaliador4', 'Rec Av4', 'IAA', 'IEG', 'IPS', 'Rec Psicologia', 'IDA',
       'Matem', 'Portug', 'Inglês', 'Indicado', 'Atingiu PV', 'IPV', 'IAN',
       'Fase ideal', 'Defas', 'Destaque IEG', 'Destaque IDA', 'Destaque IPV'],
      dtype='object')

In [268]:
#Ajustando nomes identicos entre as baeses
base_2022 = base_2022.rename(columns={
    'Nome': 'Nome Anonimizado',
    'Idade 22': 'Idade',
    'Matem': 'Mat',
    'Portug': 'Por',
    'Inglês': 'Ing',
    'Defas': 'Defasagem',
    'Pedra 22': 'Pedra',
    'INDE 22': 'INDE'
})


#Ajustando nomes identicos entre as baeses
base_2023 = base_2023.rename(columns={
    'Pedra 2023': 'Pedra',
    'INDE 2023': 'INDE'
})

#Ajustando nomes identicos entre as baeses
base_2024 = base_2024.rename(columns={
    'Pedra 2024': 'Pedra',
    'INDE 2024': 'INDE'
})

In [269]:
#Criando coluna para ANO
base_2022['Ano_Aba'] = 2022
base_2022['Ano_Aba'] = base_2022['Ano_Aba'].astype(int)

base_2023['Ano_Aba'] = 2023
base_2023['Ano_Aba'] = base_2023['Ano_Aba'].astype(int)

base_2024['Ano_Aba'] = 2024
base_2024['Ano_Aba'] = base_2024['Ano_Aba'].astype(int)

In [270]:
#remover colunas dos dataframes 2022 
colunas_remover2022 = ['Ano nasc','Cg','Cf','Ct','Pedra 20','Pedra 21'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Rec Av3','Avaliador4'
                   ,'Rec Av4','Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV']

base_2022.drop(columns=colunas_remover2022, inplace=True)

In [271]:
#remover colunas dos dataframes 2023 
colunas_remover2023 = ['Data de Nasc','Pedra 20', 'Pedra 21','Pedra 22','Pedra 23','INDE 22','INDE 23','Cg','Cf','Ct'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Rec Av3','Avaliador4'
                   ,'Rec Av4','Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV','Destaque IPV.1']

base_2023.drop(columns=colunas_remover2023, inplace=True)

In [272]:
#remover colunas dos dataframes 2024 
colunas_remover2024 = ['Data de Nasc','Pedra 20', 'Pedra 21','Pedra 22','Pedra 23','INDE 22','INDE 23','Cg','Cf','Ct'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Avaliador4','Avaliador5'
                   ,'Avaliador6', 'Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV','Escola','Ativo/ Inativo','Ativo/ Inativo.1']

base_2024.drop(columns=colunas_remover2024, inplace=True)

## Ajustes nas colunas

In [273]:
# Vamos padronizar os nomes das colunas
base_2022 = funcoes.normalizar_colunas(base_2022)
base_2023 = funcoes.normalizar_colunas(base_2023)
base_2024 = funcoes.normalizar_colunas(base_2024)

<div class="alert alert-block alert-info">
⚠️ **IMPORTANTE VALIDAR  ALTERACAO QUE VITOR REALIZOU**
</div>

In [274]:
#Não identifiquei mas por "dedução fiz um de para na coluna FASE na base 2024"
""" 
Alterado de:
array(['ALFA', '1A', '1B', '1C', '1D', '1E', '1G', '1H', '1J', '1K', '1L', '1M', '1N', '1P', '1R', '2A', '2B', '2C', '2D', '2G', '2H'
        , '2I', '2K', '2L', '2M', '2N', '2P', '2R', '2U', '3A', '3B', '3C', '3D', '3F', '3G', '3H', '3I', '3K', '3L', '3M', '3N', '3P'
        , '3R', '3U', '4A', '4B', '4C', '4F', '4H', '4L', '4M', '4N', '4R', '5A', '5B', '5C', '5D', '5F', '5G', '5L', '5M', '5N', '6A'
        , '6L', '7A', '7E', '8A', '8B', '8D', '8E', '8F', 9], dtype=object) 

Para: array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', 'FASE 9'], dtype=object) 
"""

base_2024 = base_2024.rename(columns={"fase": "fase_original"})
base_2024["fase"] = base_2024["fase_original"].map(funcoes.normalizar_fase)

In [275]:
base_2022 = base_2022.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2022["fase_ideal"] = base_2022["fase_ideal_original"].map(funcoes.remover_texto_parenteses)

base_2023 = base_2023.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2023["fase_ideal"] = base_2023["fase_ideal_original"].map(funcoes.remover_texto_parenteses)

base_2024 = base_2024.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2024["fase_ideal"] = base_2024["fase_ideal_original"].map(funcoes.remover_texto_parenteses)

In [276]:
""" # Renomeando algumas colunas das bases
mapa = {
    'pedra_23': 'ignorar' #tem uma coluna "repetida no dataframe, vamos ignorar ela pq não tem a info que precisamos"
    ,'pedra_2023': 'pedra_23'
    ,'inde_23': 'ignorar2'
    ,'inde_2023': 'inde_23'
}
base_2023 = renomear_colunas(base_2023, mapa)

mapa = {
    'portug': 'por'
    ,'ingles': 'ing'
    ,'matem': 'mat'
    ,'defas': 'defasagem'
    ,'idade_22': 'idade'
    
}
base_2022 = renomear_colunas(base_2022, mapa) """

' # Renomeando algumas colunas das bases\nmapa = {\n    \'pedra_23\': \'ignorar\' #tem uma coluna "repetida no dataframe, vamos ignorar ela pq não tem a info que precisamos"\n    ,\'pedra_2023\': \'pedra_23\'\n    ,\'inde_23\': \'ignorar2\'\n    ,\'inde_2023\': \'inde_23\'\n}\nbase_2023 = renomear_colunas(base_2023, mapa)\n\nmapa = {\n    \'portug\': \'por\'\n    ,\'ingles\': \'ing\'\n    ,\'matem\': \'mat\'\n    ,\'defas\': \'defasagem\'\n    ,\'idade_22\': \'idade\'\n\n}\nbase_2022 = renomear_colunas(base_2022, mapa) '

In [277]:
""" # Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023['ra'].unique().tolist()
ra_2022_diferentes = base_2022['ra'].unique().tolist()

# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

base_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes) """

" # Vamos guardar os id em listas para usar depois\nra_2023_diferentes = base_2023['ra'].unique().tolist()\nra_2022_diferentes = base_2022['ra'].unique().tolist()\n\n# listamos as colunas do dataframe principal (ano de 2024)\ncolunas_finais = list(base_2024.columns) + ['ano_dataframe']\n\nbase_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)\nbase_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes) "

In [278]:
base_anos = pd.concat(
    [base_2022, base_2023, base_2024],
    axis=0,        # empilha linhas
    ignore_index=True,
    sort=False     # mantém todas as colunas
)

In [279]:
base_anos.columns

Index(['ra', 'fase', 'turma', 'nome_anonimizado', 'idade', 'genero',
       'ano_ingresso', 'instituicao_de_ensino', 'pedra', 'inde', 'no_av',
       'iaa', 'ieg', 'ips', 'ida', 'mat', 'por', 'ing', 'ipv', 'ian',
       'fase_ideal_original', 'defasagem', 'ano_aba', 'fase_ideal', 'ipp',
       'fase_original'],
      dtype='object')

In [280]:
base_anos.describe

<bound method NDFrame.describe of            ra    fase turma nome_anonimizado idade     genero  ano_ingresso  \
0        RA-1       7     A          Aluno-1    19     Menina          2016
1        RA-2       7     A          Aluno-2    17     Menina          2017
2        RA-3       7     A          Aluno-3    17     Menina          2016
3        RA-4       7     A          Aluno-4    17     Menino          2017
4        RA-5       7     A          Aluno-5    17     Menina          2016
...       ...     ...   ...              ...   ...        ...           ...
3025  RA-1658  FASE 9     9       Aluno-1658    21  Masculino          2021
3026  RA-1659  FASE 9     9       Aluno-1659    21  Masculino          2021
3027  RA-1252  FASE 9     9       Aluno-1252    22   Feminino          2021
3028  RA-1660  FASE 9     9       Aluno-1660    24   Feminino          2021
3029  RA-1661  FASE 9     9       Aluno-1661    21   Feminino          2021

                    instituicao_de_ensino     pedra     inde  ...  por  ing  \
0                          Escola Pública   Quartzo    5.783  ...  3.5  6.0
1                            Rede Decisão  Ametista    7.055  ...  4.5  9.7
2                            Rede Decisão     Ágata    6.591  ...  4.0  6.9
3                            Rede Decisão   Quartzo    5.951  ...  3.5  8.7
4                            Rede Decisão  Ametista    7.427  ...  2.9  5.7
...                                   ...       ...      ...  ...  ...  ...
3025                              Privada   INCLUIR  INCLUIR  ...  NaN  NaN
3026  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN
3027                              Privada   INCLUIR  INCLUIR  ...  NaN  NaN
3028  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN
3029  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN

        ipv   ian      fase_ideal_original  defasagem  ano_aba  fase_ideal  \
0     7.278   5.0  Fase 8 (Universitários)         -1     2022      FASE 8
1     6.778  10.0           Fase 7 (3º EM)          0     2022      FASE 7
2     7.556  10.0           Fase 7 (3º EM)          0     2022      FASE 7
3     5.278  10.0           Fase 7 (3º EM)          0     2022      FASE 7
4     7.389  10.0           Fase 7 (3º EM)          0     2022      FASE 7
...     ...   ...                      ...        ...      ...         ...
3025    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3026    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3027    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3028    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3029    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8

      ipp  fase_original
0     NaN            NaN
1     NaN            NaN
2     NaN            NaN
3     NaN            NaN
4     NaN            NaN
...   ...            ...
3025  NaN              9
3026  NaN              9
3027  NaN              9
3028  NaN              9
3029  NaN              9

[3030 rows x 26 columns]>

In [281]:
base_anos.to_excel('base_anos.xlsx', index=False)
print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

Arquivo 'meus_dados.xlsx' criado com sucesso!

### Vamos excluir os que não possuem nenhum tipo de informação em Pedra?

In [282]:
base_filtrado = base_anos[
    base_anos['pedra'].isna() |
    (base_anos['pedra'].astype(str).str.strip() == '') |
    (base_anos['pedra'].astype(str).str.strip() == 'INCLUIR')
]

In [283]:
base_filtrado.count

<bound method DataFrame.count of            ra    fase turma nome_anonimizado idade     genero  ano_ingresso  \
1414  RA-1126  FASE 2    2M       Aluno-1126    12   Feminino          2023
1649   RA-145  FASE 4    4H        Aluno-145    17  Masculino          2017
1650  RA-1188  FASE 4    4H       Aluno-1188    15   Feminino          2023
1651   RA-265  FASE 4    4H        Aluno-265    14  Masculino          2019
1652   RA-254  FASE 4    4H        Aluno-254    15  Masculino          2019
...       ...     ...   ...              ...   ...        ...           ...
3025  RA-1658  FASE 9     9       Aluno-1658    21  Masculino          2021
3026  RA-1659  FASE 9     9       Aluno-1659    21  Masculino          2021
3027  RA-1252  FASE 9     9       Aluno-1252    22   Feminino          2021
3028  RA-1660  FASE 9     9       Aluno-1660    24   Feminino          2021
3029  RA-1661  FASE 9     9       Aluno-1661    21   Feminino          2021

                    instituicao_de_ensino    pedra     inde  ...  por  ing  \
1414                              Pública      NaN      NaN  ...  NaN  NaN
1649                              Pública      NaN      NaN  ...  6.0  7.2
1650                              Pública      NaN      NaN  ...  7.5  5.2
1651                              Pública      NaN      NaN  ...  6.8  6.8
1652                              Pública      NaN      NaN  ...  5.7  6.2
...                                   ...      ...      ...  ...  ...  ...
3025                              Privada  INCLUIR  INCLUIR  ...  NaN  NaN
3026  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN
3027                              Privada  INCLUIR  INCLUIR  ...  NaN  NaN
3028  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN
3029  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN

         ipv   ian      fase_ideal_original  defasagem  ano_aba  fase_ideal  \
1414  7.0600   5.0     Fase 3 (7° e 8° ano)         -1     2023      FASE 3
1649  7.4625   2.5           Fase 7 (3° EM)         -3     2023      FASE 7
1650  7.5875   5.0           Fase 5 (1° EM)         -1     2023      FASE 5
1651  7.8800  10.0          Fase 4 (9° ano)          0     2023      FASE 4
1652  7.7100   5.0           Fase 5 (1° EM)         -1     2023      FASE 5
...      ...   ...                      ...        ...      ...         ...
3025     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3026     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3027     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3028     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3029     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8

           ipp  fase_original
1414  7.291667            NaN
1649  7.968750            NaN
1650  7.812500            NaN
1651  7.968750            NaN
1652  7.812500            NaN
...        ...            ...
3025       NaN              9
3026       NaN              9
3027       NaN              9
3028       NaN              9
3029       NaN              9

[185 rows x 26 columns]>

In [284]:
base_anos_limpo = base_anos.drop(index=base_filtrado.index)

In [285]:
base_anos_limpo.to_excel('base_anos_limpo.xlsx', index=False)
print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

Arquivo 'meus_dados.xlsx' criado com sucesso!

In [286]:
base_anos_limpo['pedra'].unique()

array(['Quartzo', 'Ametista', 'Ágata', 'Topázio', 'Agata'], dtype=object)

In [287]:
#Ajustando o nome da Pedra para mantermos um padrão definido no documento da Passos Magicos
base_anos_limpo['pedra'] = base_anos_limpo['pedra'].replace('Agata', 'Ágata')

In [288]:
base_anos_limpo['pedra'].unique()

array(['Quartzo', 'Ametista', 'Ágata', 'Topázio'], dtype=object)

In [289]:
base_2022[['nome_anonimizado','ian']]

    nome_anonimizado   ian
0            Aluno-1   5.0
1            Aluno-2  10.0
2            Aluno-3  10.0
3            Aluno-4  10.0
4            Aluno-5  10.0
..               ...   ...
855        Aluno-856  10.0
856        Aluno-857   5.0
857        Aluno-858  10.0
858        Aluno-859  10.0
859        Aluno-860  10.0

[860 rows x 2 columns]

In [290]:
base_2023[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0           Aluno-861  10.0
1           Aluno-862   5.0
2           Aluno-863  10.0
3           Aluno-864  10.0
4           Aluno-865  10.0
...               ...   ...
1009          Aluno-2  10.0
1010       Aluno-1271  10.0
1011       Aluno-1272  10.0
1012       Aluno-1273  10.0
1013       Aluno-1274  10.0

[1014 rows x 2 columns]

In [291]:
base_2024[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0          Aluno-1275  10.0
1          Aluno-1276  10.0
2          Aluno-1277  10.0
3           Aluno-868   5.0
4          Aluno-1278   5.0
...               ...   ...
1151       Aluno-1658  10.0
1152       Aluno-1659  10.0
1153       Aluno-1252  10.0
1154       Aluno-1660  10.0
1155       Aluno-1661  10.0

[1156 rows x 2 columns]

In [292]:
# Renomeando a coluna ian em cada dataframe
df_2022 = base_2022.rename(columns={"ian": "ian_2022"})
df_2023 = base_2023.rename(columns={"ian": "ian_2023"})
df_2024 = base_2024.rename(columns={"ian": "ian_2024"})

# Merge 2022 com 2023
df_merge = pd.merge(
    df_2022[["nome_anonimizado", "ian_2022"]],
    df_2023[["nome_anonimizado", "ian_2023"]],
    on="nome_anonimizado",
    how="outer"   # use 'inner' se quiser apenas quem existe nos dois anos
)

# Merge com 2024
df_final = pd.merge(
    df_merge,
    df_2024[["nome_anonimizado", "ian_2024"]],
    on="nome_anonimizado",
    how="outer"
)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024
0          Aluno-1       5.0      10.0      10.0
1         Aluno-10       5.0       NaN       NaN
2        Aluno-100      10.0       NaN       NaN
3       Aluno-1000       NaN      10.0      10.0
4       Aluno-1001       NaN       5.0       5.0

In [293]:
df_final.describe

<bound method NDFrame.describe of      nome_anonimizado  ian_2022  ian_2023  ian_2024
0             Aluno-1       5.0      10.0      10.0
1            Aluno-10       5.0       NaN       NaN
2           Aluno-100      10.0       NaN       NaN
3          Aluno-1000       NaN      10.0      10.0
4          Aluno-1001       NaN       5.0       5.0
...               ...       ...       ...       ...
1656        Aluno-995       NaN       5.0       5.0
1657        Aluno-996       NaN       5.0       NaN
1658        Aluno-997       NaN      10.0       NaN
1659        Aluno-998       NaN       5.0       NaN
1660        Aluno-999       NaN       5.0       NaN

[1661 rows x 4 columns]>

In [294]:
def valores_iguais(row):
    valores = row.dropna().unique()
    return len(valores) <= 1  # 0 ou 1 valor distinto → todos iguais

df_final["ian_igual_todos_anos"] = df_final[
    ["ian_2022","ian_2023", "ian_2024"]
].apply(valores_iguais, axis=1)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024  ian_igual_todos_anos
0          Aluno-1       5.0      10.0      10.0                 False
1         Aluno-10       5.0       NaN       NaN                  True
2        Aluno-100      10.0       NaN       NaN                  True
3       Aluno-1000       NaN      10.0      10.0                  True
4       Aluno-1001       NaN       5.0       5.0                  True

In [295]:
df_ian_2022_menor_10 = df_final[df_final["ian_2022"] < 10]

qtdeIAN_2022 = df_ian_2022_menor_10.shape[0]
print(f"{qtdeIAN_2022} - Alunos em 2023 estao moderadamente ou severamente defasados")

qtd_Total_2022 = df_final["ian_2022"].count()
print(f"Quantidade total de registros com ian_2022 preenchido: {qtd_Total_2022}")


df_ian_2023_menor_10 = df_final[df_final["ian_2023"] < 10]

qtdeIAN_2023 = df_ian_2023_menor_10.shape[0]
print(f"{qtdeIAN_2023} - Alunos em 2023 estao moderadamente ou severamente defasados")

qtd_Total_2023 = df_final["ian_2023"].count()
print(f"Quantidade total de registros com ian_2023 preenchido: {qtd_Total_2023}")


df_ian_2024_menor_10 = df_final[df_final["ian_2024"] < 10]

qtdeIAN_2024 = df_ian_2024_menor_10.shape[0]
print(f"{qtdeIAN_2024} - Alunos em 2024 estao moderadamente ou severamente defasados")

qtd_Total_2024 = df_final["ian_2024"].count()
print(f"Quantidade total de registros com ian_2024 preenchido: {qtd_Total_2024}")


#534

601 - Alunos em 2023 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2022 preenchido: 860
552 - Alunos em 2023 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2023 preenchido: 1014
534 - Alunos em 2024 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2024 preenchido: 1156

## Analise

1. Adequação do nível (IAN): Qual é o perfil geral de defasagem dos
alunos (IAN) e como ele evolui ao longo do ano?
(Ex.: quantos alunos estão moderadamente ou severamente defasados?)



IAN (Indicador de Adequação de Nível)

Fórmula: D = Fase Efetiva - Fase Ideal

Dados necessários:
-	Fase atual do estudante na Associação
-	Fase ideal conforme a idade


-	Fase ideal: 7 ano
-	Fase efetiva: 5 ano
-	Exemplo: 
-	D = 5 - 7 = -2
-	Resultado: 
-	Moderada = 5 pontos

In [296]:
base_2022[['nome_anonimizado','ida','fase','fase_ideal']]

    nome_anonimizado  ida  fase fase_ideal
0            Aluno-1  4.0     7     FASE 8
1            Aluno-2  6.8     7     FASE 7
2            Aluno-3  5.6     7     FASE 7
3            Aluno-4  5.0     7     FASE 7
4            Aluno-5  5.2     7     FASE 7
..               ...  ...   ...        ...
855        Aluno-856  8.4     0       ALFA
856        Aluno-857  9.5     0     FASE 1
857        Aluno-858  7.7     0       ALFA
858        Aluno-859  8.9     0       ALFA
859        Aluno-860  8.1     0       ALFA

[860 rows x 4 columns]

In [297]:
base_2023[['nome_anonimizado','ida','fase','fase_ideal']]

     nome_anonimizado  ida    fase fase_ideal
0           Aluno-861  9.6    ALFA       ALFA
1           Aluno-862  8.9    ALFA     FASE 1
2           Aluno-863  6.3    ALFA       ALFA
3           Aluno-864  6.3    ALFA       ALFA
4           Aluno-865  7.4    ALFA       ALFA
...               ...  ...     ...        ...
1009          Aluno-2  NaN  FASE 8     FASE 8
1010       Aluno-1271  NaN  FASE 8     FASE 8
1011       Aluno-1272  NaN  FASE 8     FASE 8
1012       Aluno-1273  NaN  FASE 8     FASE 7
1013       Aluno-1274  NaN  FASE 8     FASE 8

[1014 rows x 4 columns]

In [298]:
base_2024[['nome_anonimizado','ida','fase','fase_ideal']]

     nome_anonimizado  ida    fase fase_ideal
0          Aluno-1275  8.0    ALFA       ALFA
1          Aluno-1276  8.0    ALFA       ALFA
2          Aluno-1277  8.0    ALFA       ALFA
3           Aluno-868  7.0    ALFA     FASE 1
4          Aluno-1278  7.5    ALFA     FASE 1
...               ...  ...     ...        ...
1151       Aluno-1658  NaN  FASE 9     FASE 8
1152       Aluno-1659  NaN  FASE 9     FASE 8
1153       Aluno-1252  NaN  FASE 9     FASE 8
1154       Aluno-1660  NaN  FASE 9     FASE 8
1155       Aluno-1661  NaN  FASE 9     FASE 8

[1156 rows x 4 columns]

In [299]:
# Renomeando a coluna ian em cada dataframe
df_ida_2022 = base_2022.rename(columns={
    "ida": "ida_2022",
    "fase": "fase_2022",
    "fase_ideal": "fase_ideal_2022"
})

df_ida_2023 = base_2023.rename(columns={
    "ida": "ida_2023",
    "fase": "fase_2023",
    "fase_ideal": "fase_ideal_2023"
})

df_ida_2024 = base_2024.rename(columns={
    "ida": "ida_2024",
    "fase": "fase_2024",
    "fase_ideal": "fase_ideal_2024"
})

# Merge 2022 com 2023
df_merge_ida = pd.merge(
    df_ida_2022[["nome_anonimizado", "ida_2022","fase_2022","fase_ideal_2022"]],
    df_ida_2023[["nome_anonimizado", "ida_2023","fase_2023","fase_ideal_2023"]],
    on="nome_anonimizado",
    how="outer"   # use 'inner' se quiser apenas quem existe nos dois anos
)

# Merge com 2024
df_final_ida = pd.merge(
    df_merge_ida,
    df_ida_2024[["nome_anonimizado", "ida_2024","fase_2024","fase_ideal_2024"]],
    on="nome_anonimizado",
    how="outer"
)

df_final_ida.head()

,nome_anonimizado,ida_2022,fase_2022,fase_ideal_2022,ida_2023,fase_2023,fase_ideal_2023,ida_2024,fase_2024,fase_ideal_2024
0,Aluno-1,4.0,7.0,FASE 8,NaN,FASE 8,FASE 8,NaN,FASE 8,FASE 8
1,Aluno-10,4.1,7.0,FASE 8,NaN,NaN,NaN,NaN,NaN,NaN
2,Aluno-100,7.6,4.0,FASE 3,NaN,NaN,NaN,NaN,NaN,NaN
3,Aluno-1000,NaN,NaN,NaN,7.0,ALFA,ALFA,7.75,FASE 1,FASE 1
4,Aluno-1001,NaN,NaN,NaN,7.8,ALFA,FASE 1,7.75,FASE 1,FASE 2

In [300]:
base_2022["fase"].unique()

array([7, 6, 5, 4, 3, 2, 1, 0])

In [301]:
base_2023["fase"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [302]:
base_2024["fase"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8', 'FASE 9'], dtype=object)

In [303]:
base_2022["fase_ideal"].unique()

array(['FASE 8', 'FASE 7', 'FASE 6', 'FASE 5', 'FASE 3', 'FASE 4',
       'FASE 2', 'FASE 1', 'ALFA'], dtype=object)

In [304]:
base_2023["fase_ideal"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [305]:
base_2024["fase_ideal"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 6', 'FASE 5',
       'FASE 7', 'FASE 8'], dtype=object)

In [306]:
df_divergentes = df_final[df_final["ian_igual_todos_anos"] == False]

df_divergentes.describe

df_divergentes

     nome_anonimizado  ian_2022  ian_2023  ian_2024  ian_igual_todos_anos
0             Aluno-1       5.0      10.0      10.0                 False
6          Aluno-1003       NaN      10.0       5.0                 False
7          Aluno-1004       NaN      10.0       5.0                 False
9          Aluno-1006       NaN      10.0       5.0                 False
11         Aluno-1008       NaN      10.0       5.0                 False
...               ...       ...       ...       ...                   ...
1637        Aluno-978       NaN      10.0       5.0                 False
1638        Aluno-979       NaN      10.0       5.0                 False
1641        Aluno-981       NaN      10.0       5.0                 False
1649        Aluno-989       NaN       5.0      10.0                 False
1655        Aluno-994       NaN      10.0       5.0                 False

[400 rows x 5 columns]

## Juntando os dataframes

In [307]:
# Vamos juntar os dataframes, mas primeiro vamos evitar juntar casos que já estão 2024
ra_principal = set(base_2024['ra'])

base_2023_filtrado = base_2023[
    (~base_2023['ra'].isin(ra_principal)) #alguns valores estão com problemas,
]

ra_principal.update(base_2023_filtrado['ra'].unique()) #marca os de 2023 para evitar duplicados que tem apenas entre 23 e 22

base_2022_filtrado = base_2022[
    (~base_2022['ra'].isin(ra_principal))
]

# Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023_filtrado['ra'].unique().tolist()
ra_2022_diferentes = base_2022_filtrado['ra'].unique().tolist()

In [308]:
# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

# Colocamos as colunas nos dataframes, para que eles fiquem 'parecidos' com 2024, e também uma coluna para saber de qual ano veio a info
base_2024['ano_dataframe'] = 2024
base_2023 = funcoes.adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = funcoes.adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes)

In [309]:
# Após todos os tratamentos, juntamos tudo
df_unificado = pd.concat(
    [base_2024, base_2023, base_2022],
    ignore_index=True
)

## Limpeza e correção dos dados dataframe

In [310]:
df_unificado.head()

,ra,fase_original,inde,pedra,turma,nome_anonimizado,idade,genero,ano_ingresso,instituicao_de_ensino,...,por,ing,ipv,ian,fase_ideal_original,defasagem,ano_aba,fase,fase_ideal,ano_dataframe
0,RA-1275,ALFA,7.611367,Ametista,ALFA A - G0/G1,Aluno-1275,8,Masculino,2024,Pública,...,6.0,NaN,5.446667,10.0,ALFA (1° e 2° ano),0,2024,ALFA,ALFA,2024
1,RA-1276,ALFA,8.002867,Topázio,ALFA A - G0/G1,Aluno-1276,8,Feminino,2024,Pública,...,6.0,NaN,7.050000,10.0,ALFA (1° e 2° ano),0,2024,ALFA,ALFA,2024
2,RA-1277,ALFA,7.9522,Ametista,ALFA A - G0/G1,Aluno-1277,8,Masculino,2024,Pública,...,6.0,NaN,7.046667,10.0,ALFA (1° e 2° ano),0,2024,ALFA,ALFA,2024
3,RA-868,ALFA,7.156367,Ametista,ALFA A - G0/G1,Aluno-868,8,Masculino,2023,Pública,...,6.0,NaN,7.213333,5.0,Fase 1 (3° e 4° ano),-1,2024,ALFA,FASE 1,2024
4,RA-1278,ALFA,5.4442,Quartzo,ALFA A - G0/G1,Aluno-1278,9,Masculino,2024,Pública,...,7.0,NaN,4.173333,5.0,Fase 1 (3° e 4° ano),-1,2024,ALFA,FASE 1,2024

In [312]:
# Primeiro vamos corrigir o tipo de algumas colunas
colunas_correcao = ['inde']
df_unificado = funcoes.corrigir_dados('float', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser float

colunas_correcao = ['idade']
df_unificado = funcoes.corrigir_dados('int', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser data

In [315]:
# Retirando colunas com valores apenas vazios, após análises não vi valor em manter ou tentar preencher
df_unificado = funcoes.colunas_totalmente_vazias(df_unificado)
df_unificado = df_unificado.drop(columns=['avaliador1','avaliador2','avaliador3','avaliador4','avaliador5','avaliador6'], errors='ignore') #essas colunas não trazem nenhum valor para a análise

In [317]:
# Correções e ajustes no valores da tabela
df_unificado = funcoes.arredondar_floats(df_unificado)