In [166]:
import pandas as pd
import unicodedata
import re

# 0 Funcoes

In [167]:
# Como estamos importando de um excel, vamos ter que ajustar o nome das colunas
def normalizar_colunas(df):
    def remover_acentos(texto):
        return ''.join(
            c for c in unicodedata.normalize('NFKD', texto)
            if not unicodedata.combining(c)
        )

    df = df.copy()
    df.columns = [
        remover_acentos(col)
            .lower()
            .replace(' ', '_')
        for col in df.columns
    ]

    return df

In [168]:
# Como vamos juntar alguns dataframes, é melhor que estejam com os mesmos nomes algumas colunas
def renomear_colunas(df, mapa_colunas):
    """
    Parâmetros:
    df (pd.DataFrame): DataFrame original
    mapa_colunas (dict): {'nome_antigo': 'nome_novo'}

    Retorna:
    pd.DataFrame: DataFrame com colunas renomeadas
    """
    df = df.copy()

    # Aplica somente às colunas que existem no DataFrame
    mapa_valido = {
        col_antiga: col_nova
        for col_antiga, col_nova in mapa_colunas.items()
        if col_antiga in df.columns
    }

    df.rename(columns=mapa_valido, inplace=True)
    return df

In [169]:
"""
Como os dataframes tem colunas diferentes, na hora de juntar essa função irá ajudar.
Iremos adicionar colunas nos outros dataframes para que a junção possa ocorrer (as colunas terão dasdos vazios)
"""
def adaptar_dataframe(df, colunas_base, origem, lista_ids):
    df=df.copy()

     # filtra apenas os IDs desejados
    df = df[df['ra'].isin(lista_ids)]

    # adiciona colunas que faltam
    for col in colunas_base:
        if col not in df.columns:
            df[col] = pd.NA

    # mantém apenas as colunas do principal
    df = df[colunas_base]

    # cria coluna de origem
    df['ano_dataframe'] = origem

    return df

In [170]:
# Função correção de tipo de colunas
def corrigir_dados(tipo, dataframe, colunas):
    """
    Corrige o tipo de dados de colunas de um DataFrame.

    Parâmetros:
    tipo (str): tipo alvo ('int', 'float', 'str', 'data')
    dataframe (pd.DataFrame): DataFrame original
    colunas (list ou str): coluna ou lista de colunas

    Retorna:
    pd.DataFrame: DataFrame com colunas corrigidas
    """
    df = dataframe.copy()

    if isinstance(colunas, str):
        colunas = [colunas]

    match tipo.lower():
        case 'int':
            for col in colunas:
                df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

        case 'float':
            for col in colunas:
                df[col] = pd.to_numeric(df[col], errors='coerce')

        case 'str':
            for col in colunas:
                df[col] = df[col].astype(str).str.strip()

        case 'data' | 'datetime':
            for col in colunas:
                df[col] = pd.to_datetime(df[col], errors='coerce')

        case _:
            raise ValueError(
                f"Tipo '{tipo}' não suportado. "
                "Use: int, float, str, data"
            )

    return df

In [171]:
def colunas_totalmente_vazias(df):
    """
    Identifica colunas que possuem apenas valores vazios e deleta

    Parâmetros:
    df (pd.DataFrame): DataFrame de entrada
    remover (bool): se True, remove as colunas vazias

    Retorna:
    pd.DataFrame:
        - DataFrame sem colunas vazias (remover=True)
    """
    df_tmp = df.copy()

    # considera strings vazias como NaN
    df_tmp = df_tmp.replace(r'^\s*$', pd.NA, regex=True)

    colunas_vazias = [
        col for col in df_tmp.columns
        if df_tmp[col].isna().all()
    ]

    return df_tmp.drop(columns=colunas_vazias)

In [172]:
def arredondar_floats(df, casas=2):
    """
    Arredonda todas as colunas float de um DataFrame.

    Parâmetros:
    df (pd.DataFrame): DataFrame de entrada
    casas (int): número de casas decimais (padrão = 2)

    Retorna:
    pd.DataFrame: DataFrame com floats arredondados
    """
    df = df.copy()

    colunas_float = df.select_dtypes(include=['float', 'float64', 'float32']).columns

    df[colunas_float] = df[colunas_float].round(casas)

    return df

## DEF criada por VITOR

In [173]:

def normalizar_fase(valor):
    """
    Converte valores como '1A', '2C', '8F' ou 9 em 'FASE X'.
    Mantém valores sem número (ex: 'ALFA').
    """
    valor_str = str(valor)
    numeros = "".join(filter(str.isdigit, valor_str))
    
    if numeros:
        return f"FASE {numeros}"
    else:
        return valor

In [174]:
def remover_texto_parenteses(valor):
    """
    Remove qualquer texto entre parênteses e retorna o texto em MAIÚSCULO.
    Ex: 'Fase 1 (3° e 4° ano)' , 'Fase 2 (5° e 6° ano)', 'Fase 3 (7° e 8° ano)', 'Fase 4 (9° ano)',
       'Fase 6 (2° EM)', 'Fase 5 (1° EM)', 'Fase 7 (3° EM)',
       'Fase 8 (Universitários)' -> 'FASE 1', 'FASE 2', 'FASE 3', etc
    """
    if pd.isna(valor):
        return valor
    
    texto_limpo = re.sub(r"\s*\(.*?\)", "", str(valor)).strip()
    return texto_limpo.upper()

# 1 Importando os dados

In [175]:
arquivo = r"https://raw.githubusercontent.com/vbomura/tc5/0afbe2d22ee4658c81a7470b2360a2aef3cd032e/Base_Passos_Magicos/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx"

# Pegando o dado de cada aba
base_2022 = pd.read_excel(arquivo, sheet_name="PEDE2022")
base_2023 = pd.read_excel(arquivo, sheet_name="PEDE2023")
base_2024 = pd.read_excel(arquivo, sheet_name="PEDE2024")

In [176]:
base_2022.columns

Index(['RA', 'Fase', 'Turma', 'Nome', 'Ano nasc', 'Idade 22', 'Gênero',
       'Ano ingresso', 'Instituição de ensino', 'Pedra 20', 'Pedra 21',
       'Pedra 22', 'INDE 22', 'Cg', 'Cf', 'Ct', 'Nº Av', 'Avaliador1',
       'Rec Av1', 'Avaliador2', 'Rec Av2', 'Avaliador3', 'Rec Av3',
       'Avaliador4', 'Rec Av4', 'IAA', 'IEG', 'IPS', 'Rec Psicologia', 'IDA',
       'Matem', 'Portug', 'Inglês', 'Indicado', 'Atingiu PV', 'IPV', 'IAN',
       'Fase ideal', 'Defas', 'Destaque IEG', 'Destaque IDA', 'Destaque IPV'],
      dtype='object')

In [177]:
#Ajustando nomes identicos entre as baeses
base_2022 = base_2022.rename(columns={
    'Nome': 'Nome Anonimizado',
    'Idade 22': 'Idade',
    'Matem': 'Mat',
    'Portug': 'Por',
    'Inglês': 'Ing',
    'Defas': 'Defasagem',
    'Pedra 22': 'Pedra',
    'INDE 22': 'INDE'
})


#Ajustando nomes identicos entre as baeses
base_2023 = base_2023.rename(columns={
    'Pedra 2023': 'Pedra',
    'INDE 2023': 'INDE'
})

#Ajustando nomes identicos entre as baeses
base_2024 = base_2024.rename(columns={
    'Pedra 2024': 'Pedra',
    'INDE 2024': 'INDE'
})

In [178]:
#Criando coluna para ANO
base_2022['Ano_Aba'] = 2022
base_2022['Ano_Aba'] = base_2022['Ano_Aba'].astype(int)

base_2023['Ano_Aba'] = 2023
base_2023['Ano_Aba'] = base_2023['Ano_Aba'].astype(int)

base_2024['Ano_Aba'] = 2024
base_2024['Ano_Aba'] = base_2024['Ano_Aba'].astype(int)

In [179]:
#remover colunas dos dataframes 2022 
colunas_remover2022 = ['Ano nasc','Cg','Cf','Ct','Pedra 20','Pedra 21'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Rec Av3','Avaliador4'
                   ,'Rec Av4','Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV']

base_2022.drop(columns=colunas_remover2022, inplace=True)

In [180]:
#remover colunas dos dataframes 2023 
colunas_remover2023 = ['Data de Nasc','Pedra 20', 'Pedra 21','Pedra 22','Pedra 23','INDE 22','INDE 23','Cg','Cf','Ct'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Rec Av3','Avaliador4'
                   ,'Rec Av4','Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV','Destaque IPV.1']

base_2023.drop(columns=colunas_remover2023, inplace=True)

In [181]:
#remover colunas dos dataframes 2024 
colunas_remover2024 = ['Data de Nasc','Pedra 20', 'Pedra 21','Pedra 22','Pedra 23','INDE 22','INDE 23','Cg','Cf','Ct'
                   ,'Avaliador1','Rec Av1','Avaliador2','Rec Av2','Avaliador3','Avaliador4','Avaliador5'
                   ,'Avaliador6', 'Rec Psicologia','Indicado','Atingiu PV','Destaque IEG','Destaque IDA'
                   ,'Destaque IPV','Escola','Ativo/ Inativo','Ativo/ Inativo.1']

base_2024.drop(columns=colunas_remover2024, inplace=True)

## Ajustes nas colunas

In [182]:
# Vamos padronizar os nomes das colunas
base_2022 = normalizar_colunas(base_2022)
base_2023 = normalizar_colunas(base_2023)
base_2024 = normalizar_colunas(base_2024)

<div class="alert alert-block alert-info">
⚠️ **IMPORTANTE VALIDAR  ALTERACAO QUE VITOR REALIZOU**
</div>

In [184]:
#Não identifiquei mas por "dedução fiz um de para na coluna FASE na base 2024"
""" 
Alterado de:
array(['ALFA', '1A', '1B', '1C', '1D', '1E', '1G', '1H', '1J', '1K', '1L', '1M', '1N', '1P', '1R', '2A', '2B', '2C', '2D', '2G', '2H'
        , '2I', '2K', '2L', '2M', '2N', '2P', '2R', '2U', '3A', '3B', '3C', '3D', '3F', '3G', '3H', '3I', '3K', '3L', '3M', '3N', '3P'
        , '3R', '3U', '4A', '4B', '4C', '4F', '4H', '4L', '4M', '4N', '4R', '5A', '5B', '5C', '5D', '5F', '5G', '5L', '5M', '5N', '6A'
        , '6L', '7A', '7E', '8A', '8B', '8D', '8E', '8F', 9], dtype=object) 

Para: array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6', 'FASE 7', 'FASE 8', 'FASE 9'], dtype=object) 
"""

base_2024 = base_2024.rename(columns={"fase": "fase_original"})
base_2024["fase"] = base_2024["fase_original"].map(normalizar_fase)

In [185]:
base_2022 = base_2022.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2022["fase_ideal"] = base_2022["fase_ideal_original"].map(remover_texto_parenteses)

base_2023 = base_2023.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2023["fase_ideal"] = base_2023["fase_ideal_original"].map(remover_texto_parenteses)

base_2024 = base_2024.rename(columns={"fase_ideal": "fase_ideal_original"})
base_2024["fase_ideal"] = base_2024["fase_ideal_original"].map(remover_texto_parenteses)

In [186]:
""" # Renomeando algumas colunas das bases
mapa = {
    'pedra_23': 'ignorar' #tem uma coluna "repetida no dataframe, vamos ignorar ela pq não tem a info que precisamos"
    ,'pedra_2023': 'pedra_23'
    ,'inde_23': 'ignorar2'
    ,'inde_2023': 'inde_23'
}
base_2023 = renomear_colunas(base_2023, mapa)

mapa = {
    'portug': 'por'
    ,'ingles': 'ing'
    ,'matem': 'mat'
    ,'defas': 'defasagem'
    ,'idade_22': 'idade'
    
}
base_2022 = renomear_colunas(base_2022, mapa) """

' # Renomeando algumas colunas das bases\nmapa = {\n    \'pedra_23\': \'ignorar\' #tem uma coluna "repetida no dataframe, vamos ignorar ela pq não tem a info que precisamos"\n    ,\'pedra_2023\': \'pedra_23\'\n    ,\'inde_23\': \'ignorar2\'\n    ,\'inde_2023\': \'inde_23\'\n}\nbase_2023 = renomear_colunas(base_2023, mapa)\n\nmapa = {\n    \'portug\': \'por\'\n    ,\'ingles\': \'ing\'\n    ,\'matem\': \'mat\'\n    ,\'defas\': \'defasagem\'\n    ,\'idade_22\': \'idade\'\n\n}\nbase_2022 = renomear_colunas(base_2022, mapa) '

In [187]:
""" # Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023['ra'].unique().tolist()
ra_2022_diferentes = base_2022['ra'].unique().tolist()

# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

base_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes) """

" # Vamos guardar os id em listas para usar depois\nra_2023_diferentes = base_2023['ra'].unique().tolist()\nra_2022_diferentes = base_2022['ra'].unique().tolist()\n\n# listamos as colunas do dataframe principal (ano de 2024)\ncolunas_finais = list(base_2024.columns) + ['ano_dataframe']\n\nbase_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)\nbase_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes) "

In [188]:
base_anos = pd.concat(
    [base_2022, base_2023, base_2024],
    axis=0,        # empilha linhas
    ignore_index=True,
    sort=False     # mantém todas as colunas
)

In [189]:
base_anos.columns

Index(['ra', 'fase', 'turma', 'nome_anonimizado', 'idade', 'genero',
       'ano_ingresso', 'instituicao_de_ensino', 'pedra', 'inde', 'no_av',
       'iaa', 'ieg', 'ips', 'ida', 'mat', 'por', 'ing', 'ipv', 'ian',
       'fase_ideal_original', 'defasagem', 'ano_aba', 'fase_ideal', 'ipp',
       'fase_original'],
      dtype='object')

In [191]:
base_anos.describe

<bound method NDFrame.describe of            ra    fase turma nome_anonimizado idade     genero  ano_ingresso  \
0        RA-1       7     A          Aluno-1    19     Menina          2016
1        RA-2       7     A          Aluno-2    17     Menina          2017
2        RA-3       7     A          Aluno-3    17     Menina          2016
3        RA-4       7     A          Aluno-4    17     Menino          2017
4        RA-5       7     A          Aluno-5    17     Menina          2016
...       ...     ...   ...              ...   ...        ...           ...
3025  RA-1658  FASE 9     9       Aluno-1658    21  Masculino          2021
3026  RA-1659  FASE 9     9       Aluno-1659    21  Masculino          2021
3027  RA-1252  FASE 9     9       Aluno-1252    22   Feminino          2021
3028  RA-1660  FASE 9     9       Aluno-1660    24   Feminino          2021
3029  RA-1661  FASE 9     9       Aluno-1661    21   Feminino          2021

                    instituicao_de_ensino     pedra     inde  ...  por  ing  \
0                          Escola Pública   Quartzo    5.783  ...  3.5  6.0
1                            Rede Decisão  Ametista    7.055  ...  4.5  9.7
2                            Rede Decisão     Ágata    6.591  ...  4.0  6.9
3                            Rede Decisão   Quartzo    5.951  ...  3.5  8.7
4                            Rede Decisão  Ametista    7.427  ...  2.9  5.7
...                                   ...       ...      ...  ...  ...  ...
3025                              Privada   INCLUIR  INCLUIR  ...  NaN  NaN
3026  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN
3027                              Privada   INCLUIR  INCLUIR  ...  NaN  NaN
3028  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN
3029  Bolsista Universitário *Formado (a)   INCLUIR  INCLUIR  ...  NaN  NaN

        ipv   ian      fase_ideal_original  defasagem  ano_aba  fase_ideal  \
0     7.278   5.0  Fase 8 (Universitários)         -1     2022      FASE 8
1     6.778  10.0           Fase 7 (3º EM)          0     2022      FASE 7
2     7.556  10.0           Fase 7 (3º EM)          0     2022      FASE 7
3     5.278  10.0           Fase 7 (3º EM)          0     2022      FASE 7
4     7.389  10.0           Fase 7 (3º EM)          0     2022      FASE 7
...     ...   ...                      ...        ...      ...         ...
3025    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3026    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3027    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3028    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3029    NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8

      ipp  fase_original
0     NaN            NaN
1     NaN            NaN
2     NaN            NaN
3     NaN            NaN
4     NaN            NaN
...   ...            ...
3025  NaN              9
3026  NaN              9
3027  NaN              9
3028  NaN              9
3029  NaN              9

[3030 rows x 26 columns]>

In [192]:
base_anos.to_excel('base_anos.xlsx', index=False)
print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

Arquivo 'meus_dados.xlsx' criado com sucesso!

### Vamos excluir os que não possuem nenhum tipo de informação em Pedra?

In [198]:
base_filtrado = base_anos[
    base_anos['pedra'].isna() |
    (base_anos['pedra'].astype(str).str.strip() == '') |
    (base_anos['pedra'].astype(str).str.strip() == 'INCLUIR')
]

In [199]:
base_filtrado.count

<bound method DataFrame.count of            ra    fase turma nome_anonimizado idade     genero  ano_ingresso  \
1414  RA-1126  FASE 2    2M       Aluno-1126    12   Feminino          2023
1649   RA-145  FASE 4    4H        Aluno-145    17  Masculino          2017
1650  RA-1188  FASE 4    4H       Aluno-1188    15   Feminino          2023
1651   RA-265  FASE 4    4H        Aluno-265    14  Masculino          2019
1652   RA-254  FASE 4    4H        Aluno-254    15  Masculino          2019
...       ...     ...   ...              ...   ...        ...           ...
3025  RA-1658  FASE 9     9       Aluno-1658    21  Masculino          2021
3026  RA-1659  FASE 9     9       Aluno-1659    21  Masculino          2021
3027  RA-1252  FASE 9     9       Aluno-1252    22   Feminino          2021
3028  RA-1660  FASE 9     9       Aluno-1660    24   Feminino          2021
3029  RA-1661  FASE 9     9       Aluno-1661    21   Feminino          2021

                    instituicao_de_ensino    pedra     inde  ...  por  ing  \
1414                              Pública      NaN      NaN  ...  NaN  NaN
1649                              Pública      NaN      NaN  ...  6.0  7.2
1650                              Pública      NaN      NaN  ...  7.5  5.2
1651                              Pública      NaN      NaN  ...  6.8  6.8
1652                              Pública      NaN      NaN  ...  5.7  6.2
...                                   ...      ...      ...  ...  ...  ...
3025                              Privada  INCLUIR  INCLUIR  ...  NaN  NaN
3026  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN
3027                              Privada  INCLUIR  INCLUIR  ...  NaN  NaN
3028  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN
3029  Bolsista Universitário *Formado (a)  INCLUIR  INCLUIR  ...  NaN  NaN

         ipv   ian      fase_ideal_original  defasagem  ano_aba  fase_ideal  \
1414  7.0600   5.0     Fase 3 (7° e 8° ano)         -1     2023      FASE 3
1649  7.4625   2.5           Fase 7 (3° EM)         -3     2023      FASE 7
1650  7.5875   5.0           Fase 5 (1° EM)         -1     2023      FASE 5
1651  7.8800  10.0          Fase 4 (9° ano)          0     2023      FASE 4
1652  7.7100   5.0           Fase 5 (1° EM)         -1     2023      FASE 5
...      ...   ...                      ...        ...      ...         ...
3025     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3026     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3027     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3028     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8
3029     NaN  10.0  Fase 8 (Universitários)          1     2024      FASE 8

           ipp  fase_original
1414  7.291667            NaN
1649  7.968750            NaN
1650  7.812500            NaN
1651  7.968750            NaN
1652  7.812500            NaN
...        ...            ...
3025       NaN              9
3026       NaN              9
3027       NaN              9
3028       NaN              9
3029       NaN              9

[185 rows x 26 columns]>

In [200]:
base_anos_limpo = base_anos.drop(index=base_filtrado.index)

In [201]:
base_anos_limpo.to_excel('base_anos_limpo.xlsx', index=False)
print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

Arquivo 'meus_dados.xlsx' criado com sucesso!

In [203]:
base_anos_limpo['pedra'].unique()

array(['Quartzo', 'Ametista', 'Ágata', 'Topázio', 'Agata'], dtype=object)

In [204]:
#Ajustando o nome da Pedra para mantermos um padrão definido no documento da Passos Magicos
base_anos_limpo['pedra'] = base_anos_limpo['pedra'].replace('Agata', 'Ágata')

In [205]:
base_anos_limpo['pedra'].unique()

array(['Quartzo', 'Ametista', 'Ágata', 'Topázio'], dtype=object)

In [ ]:
base_2022[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0             Aluno-1   5.0
1             Aluno-2  10.0
2             Aluno-3  10.0
3             Aluno-4  10.0
4             Aluno-5  10.0
...               ...   ...
2923        Aluno-291  10.0
2924         Aluno-86  10.0
2925        Aluno-143  10.0
2926        Aluno-166  10.0
2927        Aluno-191  10.0

[2845 rows x 2 columns]

In [ ]:
base_2023[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0           Aluno-861  10.0
1           Aluno-862   5.0
2           Aluno-863  10.0
3           Aluno-864  10.0
4           Aluno-865  10.0
...               ...   ...
1009          Aluno-2  10.0
1010       Aluno-1271  10.0
1011       Aluno-1272  10.0
1012       Aluno-1273  10.0
1013       Aluno-1274  10.0

[1014 rows x 2 columns]

In [ ]:
base_2024[['nome_anonimizado','ian']]

     nome_anonimizado   ian
0          Aluno-1275  10.0
1          Aluno-1276  10.0
2          Aluno-1277  10.0
3           Aluno-868   5.0
4          Aluno-1278   5.0
...               ...   ...
1151       Aluno-1658  10.0
1152       Aluno-1659  10.0
1153       Aluno-1252  10.0
1154       Aluno-1660  10.0
1155       Aluno-1661  10.0

[1156 rows x 2 columns]

In [ ]:
# Renomeando a coluna ian em cada dataframe
df_2022 = base_2022.rename(columns={"ian": "ian_2022"})
df_2023 = base_2023.rename(columns={"ian": "ian_2023"})
df_2024 = base_2024.rename(columns={"ian": "ian_2024"})

# Merge 2022 com 2023
df_merge = pd.merge(
    df_2022[["nome_anonimizado", "ian_2022"]],
    df_2023[["nome_anonimizado", "ian_2023"]],
    on="nome_anonimizado",
    how="outer"   # use 'inner' se quiser apenas quem existe nos dois anos
)

# Merge com 2024
df_final = pd.merge(
    df_merge,
    df_2024[["nome_anonimizado", "ian_2024"]],
    on="nome_anonimizado",
    how="outer"
)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024
0          Aluno-1      10.0      10.0      10.0
1       Aluno-1000       NaN      10.0      10.0
2       Aluno-1001       NaN       5.0       5.0
3       Aluno-1002       NaN       5.0       5.0
4       Aluno-1003       NaN      10.0       5.0

In [ ]:
df_final.describe

<bound method NDFrame.describe of      nome_anonimizado  ian_2022  ian_2023  ian_2024
0             Aluno-1      10.0      10.0      10.0
1          Aluno-1000       NaN      10.0      10.0
2          Aluno-1001       NaN       5.0       5.0
3          Aluno-1002       NaN       5.0       5.0
4          Aluno-1003       NaN      10.0       5.0
...               ...       ...       ...       ...
1400        Aluno-995       NaN       5.0       5.0
1401        Aluno-996       NaN       5.0       NaN
1402        Aluno-997       NaN      10.0       NaN
1403        Aluno-998       NaN       5.0       NaN
1404        Aluno-999       NaN       5.0       NaN

[1405 rows x 4 columns]>

In [ ]:
def valores_iguais(row):
    valores = row.dropna().unique()
    return len(valores) <= 1  # 0 ou 1 valor distinto → todos iguais

df_final["ian_igual_todos_anos"] = df_final[
    ["ian_2022","ian_2023", "ian_2024"]
].apply(valores_iguais, axis=1)

df_final.head()

  nome_anonimizado  ian_2022  ian_2023  ian_2024  ian_igual_todos_anos
0          Aluno-1      10.0      10.0      10.0                  True
1       Aluno-1000       NaN      10.0      10.0                  True
2       Aluno-1001       NaN       5.0       5.0                  True
3       Aluno-1002       NaN       5.0       5.0                  True
4       Aluno-1003       NaN      10.0       5.0                 False

In [ ]:
df_ian_2022_menor_10 = df_final[df_final["ian_2022"] < 10]

qtdeIAN_2022 = df_ian_2022_menor_10.shape[0]
print(f"{qtdeIAN_2022} - Alunos em 2023 estao moderadamente ou severamente defasados")

qtd_Total_2022 = df_final["ian_2022"].count()
print(f"Quantidade total de registros com ian_2022 preenchido: {qtd_Total_2022}")


df_ian_2023_menor_10 = df_final[df_final["ian_2023"] < 10]

qtdeIAN_2023 = df_ian_2023_menor_10.shape[0]
print(f"{qtdeIAN_2023} - Alunos em 2023 estao moderadamente ou severamente defasados")

qtd_Total_2023 = df_final["ian_2023"].count()
print(f"Quantidade total de registros com ian_2023 preenchido: {qtd_Total_2023}")


df_ian_2024_menor_10 = df_final[df_final["ian_2024"] < 10]

qtdeIAN_2024 = df_ian_2024_menor_10.shape[0]
print(f"{qtdeIAN_2024} - Alunos em 2024 estao moderadamente ou severamente defasados")

qtd_Total_2024 = df_final["ian_2024"].count()
print(f"Quantidade total de registros com ian_2024 preenchido: {qtd_Total_2024}")


#534

366 - Alunos em 2023 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2022 preenchido: 600
552 - Alunos em 2023 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2023 preenchido: 1014
534 - Alunos em 2024 estao moderadamente ou severamente defasados
Quantidade total de registros com ian_2024 preenchido: 1156

## Analise

1. Adequação do nível (IAN): Qual é o perfil geral de defasagem dos
alunos (IAN) e como ele evolui ao longo do ano?
(Ex.: quantos alunos estão moderadamente ou severamente defasados?)



IAN (Indicador de Adequação de Nível)

Fórmula: D = Fase Efetiva - Fase Ideal

Dados necessários:
-	Fase atual do estudante na Associação
-	Fase ideal conforme a idade


-	Fase ideal: 7 ano
-	Fase efetiva: 5 ano
-	Exemplo: 
-	D = 5 - 7 = -2
-	Resultado: 
-	Moderada = 5 pontos

In [ ]:
base_2022[['nome_anonimizado','ida','fase','fase_ideal']]

     nome_anonimizado  ida    fase               fase_ideal
31          Aluno-684  6.5    ALFA       ALFA (1° e 2° ano)
33          Aluno-857  8.5    ALFA     Fase 1 (3° e 4° ano)
36          Aluno-690  9.1    ALFA     Fase 2 (5° e 6° ano)
39          Aluno-693  8.5    ALFA       ALFA (1° e 2° ano)
40          Aluno-675  8.3    ALFA       ALFA (1° e 2° ano)
...               ...  ...     ...                      ...
1005         Aluno-29  NaN  FASE 8  Fase 8 (Universitários)
1006         Aluno-17  NaN  FASE 8  Fase 8 (Universitários)
1007         Aluno-21  NaN  FASE 8  Fase 8 (Universitários)
1008         Aluno-25  NaN  FASE 8  Fase 8 (Universitários)
1009          Aluno-2  NaN  FASE 8  Fase 8 (Universitários)

[600 rows x 4 columns]

In [ ]:
base_2023[['nome_anonimizado','ida','fase','fase_ideal']]

     nome_anonimizado  ida    fase               fase_ideal
0           Aluno-861  9.6    ALFA       ALFA (1° e 2° ano)
1           Aluno-862  8.9    ALFA     Fase 1 (3° e 4° ano)
2           Aluno-863  6.3    ALFA       ALFA (1° e 2° ano)
3           Aluno-864  6.3    ALFA       ALFA (1° e 2° ano)
4           Aluno-865  7.4    ALFA       ALFA (1° e 2° ano)
...               ...  ...     ...                      ...
1009          Aluno-2  NaN  FASE 8  Fase 8 (Universitários)
1010       Aluno-1271  NaN  FASE 8  Fase 8 (Universitários)
1011       Aluno-1272  NaN  FASE 8  Fase 8 (Universitários)
1012       Aluno-1273  NaN  FASE 8           Fase 7 (3° EM)
1013       Aluno-1274  NaN  FASE 8  Fase 8 (Universitários)

[1014 rows x 4 columns]

In [ ]:
base_2024[['nome_anonimizado','ida','fase','fase_ideal']]

     nome_anonimizado  ida    fase               fase_ideal
0          Aluno-1275  8.0    ALFA       ALFA (1° e 2° ano)
1          Aluno-1276  8.0    ALFA       ALFA (1° e 2° ano)
2          Aluno-1277  8.0    ALFA       ALFA (1° e 2° ano)
3           Aluno-868  7.0    ALFA     Fase 1 (3° e 4° ano)
4          Aluno-1278  7.5    ALFA     Fase 1 (3° e 4° ano)
...               ...  ...     ...                      ...
1151       Aluno-1658  NaN  FASE 9  Fase 8 (Universitários)
1152       Aluno-1659  NaN  FASE 9  Fase 8 (Universitários)
1153       Aluno-1252  NaN  FASE 9  Fase 8 (Universitários)
1154       Aluno-1660  NaN  FASE 9  Fase 8 (Universitários)
1155       Aluno-1661  NaN  FASE 9  Fase 8 (Universitários)

[1156 rows x 4 columns]

In [ ]:
# Renomeando a coluna ian em cada dataframe
df_ida_2022 = base_2022.rename(columns={
    "ida": "ida_2022",
    "fase": "fase_2022",
    "fase_ideal": "fase_ideal_2022"
})

df_ida_2023 = base_2023.rename(columns={
    "ida": "ida_2023",
    "fase": "fase_2023",
    "fase_ideal": "fase_ideal_2023"
})

df_ida_2024 = base_2024.rename(columns={
    "ida": "ida_2024",
    "fase": "fase_2024",
    "fase_ideal": "fase_ideal_2024"
})

# Merge 2022 com 2023
df_merge_ida = pd.merge(
    df_ida_2022[["nome_anonimizado", "ida_2022","fase_2022","fase_ideal_2022"]],
    df_ida_2023[["nome_anonimizado", "ida_2023","fase_2023","fase_ideal_2023"]],
    on="nome_anonimizado",
    how="outer"   # use 'inner' se quiser apenas quem existe nos dois anos
)

# Merge com 2024
df_final_ida = pd.merge(
    df_merge_ida,
    df_ida_2024[["nome_anonimizado", "ida_2024","fase_2024","fase_ideal_2024"]],
    on="nome_anonimizado",
    how="outer"
)

df_final_ida.head()

,nome_anonimizado,ida_2022,fase_2022,fase_ideal_2022,ida_2023,fase_2023,fase_ideal_2023,ida_2024,fase_2024,fase_ideal_2024
0,Aluno-1,NaN,FASE 8,FASE 8,NaN,FASE 8,FASE 8,NaN,FASE 8,FASE 8
1,Aluno-1000,NaN,NaN,NaN,7.0,ALFA,ALFA,7.75,FASE 1,FASE 1
2,Aluno-1001,NaN,NaN,NaN,7.8,ALFA,FASE 1,7.75,FASE 1,FASE 2
3,Aluno-1002,NaN,NaN,NaN,7.0,ALFA,FASE 1,9.25,ALFA,FASE 1
4,Aluno-1003,NaN,NaN,NaN,4.0,ALFA,ALFA,8.25,ALFA,FASE 1

In [ ]:
base_2022["fase"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [ ]:
base_2023["fase"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [ ]:
base_2024["fase"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8', 'FASE 9'], dtype=object)

In [ ]:
base_2022["fase_ideal"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [ ]:
base_2023["fase_ideal"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 5', 'FASE 6',
       'FASE 7', 'FASE 8'], dtype=object)

In [ ]:
base_2024["fase_ideal"].unique()

array(['ALFA', 'FASE 1', 'FASE 2', 'FASE 3', 'FASE 4', 'FASE 6', 'FASE 5',
       'FASE 7', 'FASE 8'], dtype=object)

,ra,fase_original,inde_2024,pedra_2024,turma,nome_anonimizado,data_de_nasc,idade,genero,ano_ingresso,...,ian,fase_ideal,defasagem,destaque_ieg,destaque_ida,destaque_ipv,escola,ativo/_inativo,ativo/_inativo.1,fase
1017,RA-80,7A,8.131659,Topázio,7A,Aluno-80,2006-07-05,18,Feminino,2021,...,10.0,Fase 7 (3° EM),0,NaN,NaN,NaN,Colégio Arco Íris Evolução,Cursando,Cursando,FASE 7

In [ ]:
df_divergentes = df_final[df_final["ian_igual_todos_anos"] == False]

df_divergentes.describe

df_divergentes

     nome_anonimizado  ian_2022  ian_2023  ian_2024  ian_igual_todos_anos
4          Aluno-1003       NaN      10.0       5.0                 False
5          Aluno-1004       NaN      10.0       5.0                 False
7          Aluno-1006       NaN      10.0       5.0                 False
9          Aluno-1008       NaN      10.0       5.0                 False
10         Aluno-1009       NaN      10.0       5.0                 False
...               ...       ...       ...       ...                   ...
1381        Aluno-978       NaN      10.0       5.0                 False
1382        Aluno-979       NaN      10.0       5.0                 False
1385        Aluno-981       NaN      10.0       5.0                 False
1393        Aluno-989       NaN       5.0      10.0                 False
1399        Aluno-994       NaN      10.0       5.0                 False

[262 rows x 5 columns]

In [ ]:
stop

NameError: name 'stop' is not defined

## Juntando os dataframes

In [ ]:
# Vamos juntar os dataframes, mas primeiro vamos evitar juntar casos que já estão 2024
ra_principal = set(base_2024['ra'])

base_2023_filtrado = base_2023[
    (~base_2023['ra'].isin(ra_principal)) #alguns valores estão com problemas,
]

ra_principal.update(base_2023_filtrado['ra'].unique()) #marca os de 2023 para evitar duplicados que tem apenas entre 23 e 22

base_2022_filtrado = base_2022[
    (~base_2022['ra'].isin(ra_principal))
]

# Vamos guardar os id em listas para usar depois
ra_2023_diferentes = base_2023_filtrado['ra'].unique().tolist()
ra_2022_diferentes = base_2022_filtrado['ra'].unique().tolist()

In [ ]:
# listamos as colunas do dataframe principal (ano de 2024)
colunas_finais = list(base_2024.columns) + ['ano_dataframe']

# Colocamos as colunas nos dataframes, para que eles fiquem 'parecidos' com 2024, e também uma coluna para saber de qual ano veio a info
base_2024['ano_dataframe'] = 2024
base_2023 = adaptar_dataframe(base_2023,colunas_finais, 2023, ra_2023_diferentes)
base_2022 = adaptar_dataframe(base_2023,colunas_finais, 2022, ra_2022_diferentes)

In [ ]:
# Após todos os tratamentos, juntamos tudo
df_unificado = pd.concat(
    [base_2024, base_2023, base_2022],
    ignore_index=True
)

## Limpeza e correção dos dados dataframe

In [ ]:
# Primeiro vamos corrigir o tipo de algumas colunas
colunas_correcao = ['inde_2024', 'inde_22', 'inde_23']
df_unificado = corrigir_dados('float', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser float

colunas_correcao = ['data_de_nasc']
df_unificado = corrigir_dados('data', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser data

colunas_correcao = ['idade']
df_unificado = corrigir_dados('int', df_unificado, colunas_correcao) #corrigi os dados que deveriam ser data

In [ ]:
# Retirando colunas com valores apenas vazios, após análises não vi valor em manter ou tentar preencher
df_unificado = colunas_totalmente_vazias(df_unificado)
df_unificado = df_unificado.drop(columns=['avaliador1','avaliador2','avaliador3','avaliador4','avaliador5','avaliador6'], errors='ignore') #essas colunas não trazem nenhum valor para a análise

In [ ]:
# Correções e ajustes no valores da tabela
df_unificado = arredondar_floats(df_unificado)

# Testes

In [ ]:
df_unificado.sample(50)

,ra,fase,inde_2024,pedra_2024,turma,nome_anonimizado,data_de_nasc,idade,genero,ano_ingresso,...,por,ing,ipv,ian,fase_ideal,defasagem,escola,ativo/_inativo,ativo/_inativo.1,ano_dataframe
766,RA-1556,3U,6.67,Agata,3U,Aluno-1556,2010-07-31 00:00:00,14,Masculino,2024,...,NaN,4.50,7.44,10.0,Fase 3 (7° e 8° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
937,RA-1607,5D,4.90,Quartzo,5D,Aluno-1607,2008-02-28 00:00:00,16,Masculino,2024,...,0.0,0.00,6.76,5.0,Fase 6 (2° EM),-1,EE Olivia de Faria Nogueira,Cursando,Cursando,2024
681,RA-403,3K,8.01,Topázio,3K,Aluno-403,2010-07-02 00:00:00,14,Masculino,2021,...,8.0,9.00,7.61,10.0,Fase 3 (7° e 8° ano),0,EE Maria André Schunck Dona,Cursando,Cursando,2024
1316,RA-298,FASE 3,NaN,<NA>,3K,Aluno-298,2009-05-29 00:00:00,14,Masculino,2019,...,4.5,4.20,7.75,5.0,Fase 4 (9° ano),-1,NaN,NaN,NaN,2023
1169,RA-857,ALFA,NaN,<NA>,ALFA D - G2/G3,Aluno-857,2013-11-21 00:00:00,9,Feminino,2022,...,8.2,NaN,9.01,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,2023
220,RA-900,1B,8.80,Topázio,1B,Aluno-900,2015-03-18 00:00:00,9,Feminino,2023,...,9.0,NaN,8.56,10.0,Fase 1 (3° e 4° ano),0,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando,2024
509,RA-606,2M,6.65,Agata,2M,Aluno-606,2012-12-18 00:00:00,11,Masculino,2022,...,3.0,NaN,5.61,10.0,Fase 2 (5° e 6° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
385,RA-1082,2A,6.61,Agata,2A,Aluno-1082,2011-04-07 00:00:00,13,Feminino,2023,...,5.5,NaN,6.94,5.0,Fase 3 (7° e 8° ano),-1,EE Leonice de Aquino Oliveira,Cursando,Cursando,2024
155,RA-1360,ALFA,6.85,Agata,ALFA R - G0/G1,Aluno-1360,2016-04-28 00:00:00,8,Masculino,2024,...,10.0,NaN,6.42,10.0,ALFA (1° e 2° ano),0,EE Luiz Schunck,Cursando,Cursando,2024
987,RA-279,5N,9.11,Topázio,5N,Aluno-279,2009-08-25 00:00:00,15,Masculino,2021,...,8.0,10.00,8.73,10.0,Fase 4 (9° ano),1,Colégio Arco Íris Evolução,Cursando,Cursando,2024
882,RA-1593,4N,6.64,Agata,4N,Aluno-1593,2008-11-15 00:00:00,15,Masculino,2024,...,6.5,4.00,8.54,5.0,Fase 5 (1° EM),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
192,RA-1390,ALFA,8.49,Topázio,ALFA Y - G0/G1,Aluno-1390,2016-11-12 00:00:00,7,Feminino,2024,...,8.5,NaN,8.42,10.0,ALFA (1° e 2° ano),0,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando,2024
1073,RA-1259,8D,NaN,NaN,8D,Aluno-1259,2004-02-02 00:00:00,20,Feminino,2021,...,NaN,NaN,NaN,10.0,Fase 8 (Universitários),0,Universidade Santo Amaro (UNISA),Cursando,Cursando,2024
56,RA-1308,ALFA,6.88,Agata,ALFA H - G0/G1,Aluno-1308,2015-04-30 00:00:00,9,Feminino,2024,...,4.0,NaN,5.93,5.0,Fase 1 (3° e 4° ano),-1,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando,2024
680,RA-1131,3K,8.29,Topázio,3K,Aluno-1131,2011-04-19 00:00:00,13,Feminino,2023,...,7.0,10.00,7.89,10.0,Fase 3 (7° e 8° ano),0,Colégio Arco Íris Evolução,Cursando,Cursando,2024
1099,RA-1636,8E,NaN,NaN,8E,Aluno-1636,2004-06-10 03:00:00,20,Feminino,2021,...,NaN,NaN,NaN,10.0,Fase 8 (Universitários),0,Colégio Albert Einstein,Cursando,Cursando,2024
1160,RA-870,ALFA,NaN,<NA>,ALFA A - G0/G1,Aluno-870,2014-10-20 00:00:00,9,Feminino,2023,...,1.0,NaN,5.16,5.0,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,2023
682,RA-1538,3K,7.96,Ametista,3K,Aluno-1538,2010-11-29 00:00:00,13,Masculino,2021,...,6.0,8.00,7.11,10.0,Fase 2 (5° e 6° ano),1,EE Maria André Schunck Dona,Cursando,Cursando,2024
1209,RA-1005,ALFA,NaN,<NA>,ALFA V - G0/G1,Aluno-1005,2015-07-16 00:00:00,8,Masculino,2023,...,9.2,NaN,8.16,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,2023
967,RA-271,5M,7.40,Ametista,5M,Aluno-271,2007-10-16 00:00:00,17,Feminino,2022,...,7.5,9.50,6.75,5.0,Fase 6 (2° EM),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1361,RA-128,FASE 5,NaN,<NA>,5A,Aluno-128,2007-09-20 00:00:00,16,Masculino,2019,...,4.0,6.70,7.55,5.0,Fase 6 (2° EM),-1,NaN,NaN,NaN,2023
964,RA-165,5L,8.46,Topázio,5L,Aluno-165,2008-08-02 00:00:00,16,Feminino,2021,...,7.5,8.00,7.89,10.0,Fase 5 (1° EM),0,Colégio Arco Íris Evolução,Cursando,Cursando,2024
524,RA-1502,2N,6.89,Agata,2N,Aluno-1502,2012-06-23 00:00:00,12,Feminino,2024,...,7.0,NaN,7.39,5.0,Fase 3 (7° e 8° ano),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
279,RA-822,1H,5.26,Quartzo,1H,Aluno-822,2012-02-03 00:00:00,12,Masculino,2022,...,6.0,NaN,6.61,5.0,Fase 3 (7° e 8° ano),-2,EE João Ortiz Rodrigues,Cursando,Cursando,2024
1052,RA-166,7E,8.24,Topázio,7E,Aluno-166,2008-06-03 00:00:00,16,Masculino,2021,...,7.8,8.80,7.50,10.0,Fase 6 (2° EM),1,FIAP School - SP,Cursando,Cursando,2024
146,RA-972,ALFA,7.54,Ametista,ALFA Q - G2/G3,Aluno-972,2015-09-24 00:00:00,9,Masculino,2023,...,5.5,NaN,7.17,5.0,Fase 1 (3° e 4° ano),-1,EM Etelvina Delfim Simões,Cursando,Cursando,2024
316,RA-1056,1L,8.19,Topázio,1L,Aluno-1056,2014-04-30 00:00:00,10,Masculino,2023,...,8.0,NaN,8.34,5.0,Fase 2 (5° e 6° ano),-1,EM Amanda Consuelo da Cunha,Cursando,Cursando,2024
352,RA-763,1N,6.98,Agata,1N,Aluno-763,2012-12-19 00:00:00,11,Feminino,2021,...,4.0,NaN,6.82,5.0,Fase 2 (5° e 6° ano),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1172,RA-901,ALFA,NaN,<NA>,ALFA E - G2/G3,Aluno-901,2012-12-30 00:00:00,10,Masculino,2023,...,7.3,NaN,8.60,5.0,Fase 2 (5° e 6° ano),-2,NaN,NaN,NaN,2023
180,RA-1379,ALFA,6.64,Agata,ALFA U - G2/G3,Aluno-1379,2016-03-14 00:00:00,8,Masculino,2024,...,6.0,NaN,5.16,5.0,Fase 1 (3° e 4° ano),-1,EE Helio Luiz Dobrochinski Prof,Cursando,Cursando,2024
990,RA-1201,5N,8.38,Topázio,5N,Aluno-1201,2008-02-18 00:00:00,16,Masculino,2023,...,8.0,10.00,8.56,5.0,Fase 6 (2° EM),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
336,RA-1436,1M,7.59,Ametista,1M,Aluno-1436,2013-06-24 00:00:00,11,Feminino,2024,...,8.0,NaN,7.17,5.0,Fase 2 (5° e 6° ano),-1,EM Alfredo Schunk,Cursando,Cursando,2024
885,RA-459,4N,7.23,Ametista,4N,Aluno-459,2010-04-20 00:00:00,14,Masculino,2021,...,6.0,8.00,7.37,10.0,Fase 4 (9° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
686,RA-422,3K,5.54,Quartzo,3K,Aluno-422,2010-01-10 00:00:00,14,Masculino,2022,...,4.5,1.00,5.50,5.0,Fase 4 (9° ano),-1,EE Maria André Schunck Dona,Cursando,Cursando,2024
703,RA-666,3L,8.19,Topázio,3L,Aluno-666,2012-05-09 00:00:00,12,Masculino,2022,...,5.5,6.00,8.38,10.0,Fase 3 (7° e 8° ano),0,EE Maria André Schunck Dona,Cursando,Cursando,2024
1170,RA-675,ALFA,NaN,<NA>,ALFA D - G2/G3,Aluno-675,2014-09-11 00:00:00,<NA>,Masculino,2022,...,8.0,NaN,8.34,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,2023
839,RA-1582,4H,6.47,Agata,4H,Aluno-1582,2009-04-07 00:00:00,15,Masculino,2024,...,2.0,4.50,6.67,5.0,Fase 5 (1° EM),-1,EE Paschoal Carlos Magno,Cursando,Cursando,2024
604,RA-524,3C,7.03,Ametista,3C,Aluno-524,2011-09-05 00:00:00,13,Masculino,2021,...,7.5,10.00,7.39,10.0,Fase 3 (7° e 8° ano),0,EE Paschoal Carlos Magno,Cursando,Cursando,2024
826,RA-1155,4F,7.12,Ametista,4F,Aluno-1155,2009-02-18 00:00:00,15,Feminino,2023,...,8.0,0.00,8.87,5.0,Fase 5 (1° EM),-1,EE Alexandre Rodrigues Nogueira,Cursando,Cursando,2024
1183,RA-742,ALFA,NaN,<NA>,ALFA I - G2/G3,Aluno-742,2013-08-15 00:00:00,10,Feminino,2022,...,8.8,NaN,10.01,5.0,Fase 2 (5° e 6° ano),-2,NaN,NaN,NaN,2023
852,RA-1587,4L,7.34,Ametista,4L,Aluno-1587,2008-01-10 00:00:00,16,Feminino,2024,...,0.0,NaN,8.21,5.0,Fase 6 (2° EM),-2,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1364,RA-108,FASE 5,NaN,<NA>,5B,Aluno-108,2005-04-11 00:00:00,<NA>,Feminino,2019,...,3.2,2.80,5.59,5.0,Fase 7 (3° EM),-2,NaN,NaN,NaN,2023
419,RA-522,2D,8.68,Topázio,2D,Aluno-522,2013-01-08 00:00:00,11,Masculino,2021,...,8.5,NaN,7.89,10.0,Fase 2 (5° e 6° ano),0,EE Joaquim Mendes Feliz,Cursando,Cursando,2024
773,RA-1134,3U,7.76,Ametista,3U,Aluno-1134,2011-11-28 00:00:00,12,Masculino,2023,...,5.5,6.50,6.88,10.0,Fase 3 (7° e 8° ano),0,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
93,RA-1328,ALFA,8.06,Topázio,ALFA K - G0/G1,Aluno-1328,2015-11-18 00:00:00,8,Feminino,2024,...,10.0,NaN,7.83,5.0,Fase 1 (3° e 4° ano),-1,EM Amanda Consuelo da Cunha,Cursando,Cursando,2024
1037,RA-119,7E,8.09,Topázio,7E,Aluno-119,2008-06-19 00:00:00,16,Feminino,2021,...,7.5,8.55,7.50,10.0,Fase 6 (2° EM),1,Colégio Albert Einstein - SP,Cursando,Cursando,2024
240,RA-1403,1D,8.26,Topázio,1D,Aluno-1403,2013-06-08 00:00:00,11,Feminino,2024,...,10.0,NaN,8.26,5.0,Fase 2 (5° e 6° ano),-1,EE Joaquim Mendes Feliz,Cursando,Cursando,2024
841,RA-450,4L,7.53,Ametista,4L,Aluno-450,2009-03-14 00:00:00,15,Masculino,2021,...,8.5,6.00,7.58,5.0,Fase 5 (1° EM),-1,EE Donizetti Aparecido Leite Professor,Cursando,Cursando,2024
1186,RA-932,ALFA,NaN,<NA>,ALFA K - G0/G1,Aluno-932,2015-12-22 00:00:00,7,Feminino,2023,...,8.4,NaN,9.00,10.0,ALFA (1° e 2° ano),0,NaN,NaN,NaN,2023
348,RA-953,1N,7.96,Ametista,1N,Aluno-953,2015-02-04 00:00:00,9,Feminino,2023,...,9.0,NaN,7.76,10.0,Fase 1 (3° e 4° ano),0,EE Helio Luiz Dobrochinski Prof,Cursando,Cursando,2024

In [ ]:
#df_unificado.to_excel('meus_dados.xlsx', index=False)
#print("Arquivo 'meus_dados.xlsx' criado com sucesso!")

In [ ]:
base_2022[['nome_anonimizado','ian']]

Empty DataFrame
Columns: [nome_anonimizado, ian]
Index: []

In [ ]:
df_unificado.dtypes

# df_unificado['destaque_ieg'].describe()
# df_unificado['destaque_ieg'].sample(50)
# df_unificado['cg'].isna().sum()
# df.nunique().sort_values()

ra                               object
fase                             object
inde_2024                       float64
pedra_2024                       object
turma                            object
nome_anonimizado                 object
data_de_nasc             datetime64[ns]
idade                             Int64
genero                           object
ano_ingresso                      int64
instituicao_de_ensino            object
pedra_20                         object
pedra_21                         object
pedra_22                         object
pedra_23                         object
inde_22                         float64
inde_23                         float64
no_av                           float64
iaa                             float64
ieg                             float64
ips                             float64
ipp                             float64
ida                             float64
mat                             float64
por                             float64
ing                             float64
ipv                             float64
ian                             float64
fase_ideal                       object
defasagem                         int64
escola                           object
ativo/_inativo                   object
ativo/_inativo.1                 object
ano_dataframe                     int64
dtype: object